(() => {
'use strict';
const A=window.SR11;
if(!A||A.__BETA15_CORE__)return;A.__BETA15_CORE__=true;
A.VERSION='4.0.14 • Beta 15';
const ver=document.querySelector('.ver');if(ver)ver.textContent=A.VERSION;
A.TEMPLATE_MEMORY_STORE='srstudio_encartes_template_memory_v2';
A.state.partEditMode=Boolean(A.state.partEditMode);
A.state.compareOriginal=Boolean(A.state.compareOriginal);
A.state.selectedPart=A.state.selectedPart||null;
A.PART_ROLES=['NOME','IMAGEM','PRECO_RS','PRECO_REAIS','PRECO_CENTAVOS','UNIDADE','LIMITE','PRECO_APP'];
A.partLabel=r=>({NOME:'Nome',IMAGEM:'Imagem',PRECO_RS:'R$',PRECO_REAIS:'Reais',PRECO_CENTAVOS:'Centavos',UNIDADE:'Unidade',LIMITE:'Limite',PRECO_APP:'Preço APP'}[r]||r);
A.ensurePart=(e,role)=>{e.partEdits=e.partEdits||{};e.partEdits[role]=e.partEdits[role]||{dx:0,dy:0,dw:0,dh:0};return e.partEdits[role]};
A.effectiveField=(e,role,base)=>{const m=e?.partEdits?.[role]||{},s={...(base?.style||{})};for(const k of ['font','fontSize','bold','italic','color','align','vAlign','fit'])if(m[k]!==undefined)s[k]=m[k];return{x:(base?.x||0)+(Number(m.dx)||0),y:(base?.y||0)+(Number(m.dy)||0),w:Math.max(8,(base?.w||8)+(Number(m.dw)||0)),h:Math.max(8,(base?.h||8)+(Number(m.dh)||0)),style:s,autoDetected:base?.autoDetected,fit:m.fit||base?.fit||s.fit,z:Number.isFinite(Number(m.z))?Number(m.z):undefined,locked:Boolean(m.locked)}};
function hashText(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0).toString(36)}
A.templateKey=pg=>{if(!pg?.templateSlots?.length)return'';const sig=(pg.templateSlots||[]).map(s=>({i:s.index,x:Math.round(s.x),y:Math.round(s.y),w:Math.round(s.w),h:Math.round(s.h),r:Object.keys(s.fields||{}).sort()}));return 'tpl_'+hashText(JSON.stringify({w:Math.round(pg.width),h:Math.round(pg.height),slots:sig}))};
A.slotType=(pg,slot)=>{const a=(slot.w*slot.h)/(pg.width*pg.height);if(a>=.045)return'GRANDE';if(a>=.021)return'MÉDIO';return'PEQUENO'};
A.loadTemplateMemory=()=>{try{return JSON.parse(localStorage.getItem(A.TEMPLATE_MEMORY_STORE)||'{}')||{}}catch{return{}}};
A.saveTemplateMemory=m=>{try{localStorage.setItem(A.TEMPLATE_MEMORY_STORE,JSON.stringify(m));return true}catch{return false}};
A.selectedElement=()=>A.page()?.elements?.find(x=>x.id===A.state.selected)||null;
A.selectedSlot=()=>{const e=A.selectedElement();return e?.slotId?(A.page().templateSlots||[]).find(s=>s.id===e.slotId):null};
A.availableParts=()=>{const s=A.selectedSlot();return s?A.PART_ROLES.filter(r=>s.fields?.[r]):[]};
A.applyRememberedToElement=(pg,e)=>{if(!e?.slotId)return false;const slot=(pg.templateSlots||[]).find(s=>s.id===e.slotId);if(!slot)return false;const mem=A.loadTemplateMemory()[A.templateKey(pg)];if(!mem)return false;const exact=mem.slots?.[String(slot.index)]?.parts;const type=mem.types?.[A.slotType(pg,slot)]?.parts;const src=exact||type;if(!src)return false;e.partEdits=A.copy(src);return true};
A.learnTemplate=()=>{const mem=A.loadTemplateMemory();let saved=0;for(const pg of A.state.pages||[]){const key=A.templateKey(pg);if(!key)continue;const model=mem[key]||{savedAt:'',slots:{},types:{}};for(const e of pg.elements||[]){if(!e.slotId||!e.partEdits)continue;const slot=(pg.templateSlots||[]).find(s=>s.id===e.slotId);if(!slot)continue;const parts=A.copy(e.partEdits);model.slots[String(slot.index)]={parts};model.types[A.slotType(pg,slot)]={parts:A.copy(parts)};saved++}model.savedAt=new Date().toISOString();mem[key]=model}A.saveTemplateMemory(mem);A.toast(saved?('Modelo aprendido com '+saved+' bloco(s).'):'Faça alguns ajustes manuais antes de aprender o modelo.');return saved};
A.applyTemplateMemory=()=>{A.snapshot();let n=0;for(const pg of A.state.pages||[])for(const e of pg.elements||[])if(A.applyRememberedToElement(pg,e))n++;A.commit();A.toast(n?('Padrão aplicado em '+n+' produto(s).'):'Nenhum padrão salvo para este template.');return n};
A.copyPartToSimilar=()=>{const pg=A.page(),e=A.selectedElement(),slot=A.selectedSlot(),role=A.state.selectedPart;if(!e||!slot||!role||!e.partEdits?.[role])return 0;const type=A.slotType(pg,slot),src=A.copy(e.partEdits[role]);A.snapshot();let n=0;for(const x of pg.elements||[]){if(x.id===e.id||!x.slotId)continue;const s=(pg.templateSlots||[]).find(q=>q.id===x.slotId);if(!s||A.slotType(pg,s)!==type||!s.fields?.[role])continue;x.partEdits=x.partEdits||{};x.partEdits[role]=A.copy(src);n++}A.commit();A.toast(n?('Ajuste aplicado em '+n+' bloco(s) '+type.toLowerCase()+'.'):'Nenhum bloco semelhante encontrado.');return n};
A.copyProductAdjustmentsToSimilar=()=>{const pg=A.page(),e=A.selectedElement(),slot=A.selectedSlot();if(!e||!slot||!e.partEdits)return 0;const type=A.slotType(pg,slot);A.snapshot();let n=0;for(const x of pg.elements||[]){if(x.id===e.id||!x.slotId)continue;const s=(pg.templateSlots||[]).find(q=>q.id===x.slotId);if(!s||A.slotType(pg,s)!==type)continue;x.partEdits=A.copy(e.partEdits);n++}A.commit();A.toast(n?('Produto-base copiado para '+n+' bloco(s) semelhantes.'):'Nenhum bloco semelhante encontrado.');return n};
A.resetSelectedPart=()=>{const e=A.selectedElement(),r=A.state.selectedPart;if(!e||!r||!e.partEdits?.[r])return;A.snapshot();delete e.partEdits[r];A.commit()};
A.resetSelectedProduct=()=>{const e=A.selectedElement();if(!e)return;A.snapshot();delete e.partEdits;A.commit()};
A.resetCurrentPage=()=>{A.snapshot();for(const e of A.page().elements||[])delete e.partEdits;A.commit();A.toast('Ajustes manuais da página removidos.')};
A.replaceSelectedProduct=pid=>{const e=A.selectedElement();if(!e||!A.state.products.some(p=>p.id===pid))return false;A.snapshot();e.productId=pid;A.commit();return true};
A.fillCurrentPage=()=>{const pg=A.page(),used=A.usedIds(),slots=(pg.templateSlots||[]).filter(s=>!(pg.elements||[]).some(e=>e.slotId===s.id));if(!slots.length){A.toast('Não há blocos vazios nesta página.');return 0}const pool=A.state.products.filter(p=>!used.has(p.id)&&(A.state.categoryFilter==='TODAS'||(p.category||'SEM CATEGORIA')===A.state.categoryFilter));A.snapshot();let n=0;for(const slot of slots){const p=pool.shift();if(!p)break;const e={id:A.uid('e'),productId:p.id,slotId:slot.id,highlight:0};pg.elements.push(e);A.applyRememberedToElement(pg,e);n++}A.commit();A.toast(n?('Preenchidos '+n+' bloco(s) desta página.'):'Nenhum produto disponível neste filtro.');return n};
const oldPlace=A.placeProduct;A.placeProduct=(pid,pos)=>{oldPlace(pid,pos);const e=A.selectedElement();if(e?.slotId&&A.applyRememberedToElement(A.page(),e)){A.save();A.emit()}};
const oldAuto=A.autoLayout;A.autoLayout=()=>{const r=oldAuto();let n=0;for(const pg of A.state.pages||[])for(const e of pg.elements||[])if(e.slotId&&A.applyRememberedToElement(pg,e))n++;if(n){A.save();A.emit()}return r};
const oldValidate=A.validate;A.validate=()=>{const issues=oldValidate();for(const pg of A.state.pages||[]){for(const e of pg.elements||[]){if(!e.slotId||!e.partEdits)continue;const slot=(pg.templateSlots||[]).find(s=>s.id===e.slotId);if(!slot)continue;for(const [role,base] of Object.entries(slot.fields||{})){const f=A.effectiveField(e,role,base);if(f.x<0||f.y<0||f.x+f.w>pg.width||f.y+f.h>pg.height)issues.push({severity:'warn',message:pg.name+': '+A.partLabel(role)+' de um produto saiu da página.'})}}}return issues};
console.info('[SR Studio] Beta 15 core PRO ativo');
})();

(() => {
'use strict';
const A=window.SR11,E=A.E;if(!A||A.__BETA15_RENDER__)return;A.__BETA15_RENDER__=true;
const previous=A.renderCanvas;
const pos=(n,b)=>{n.style.left=b.x+'px';n.style.top=b.y+'px';n.style.width=b.w+'px';n.style.height=b.h+'px'};
const value=(role,p)=>{const q=A.priceParts(p.price);if(role==='NOME')return p.name||'';if(role==='PRECO_RS')return'R$';if(role==='PRECO_REAIS')return q.reais;if(role==='PRECO_CENTAVOS')return q.centavos;if(role==='UNIDADE')return p.unit||'UN';if(role==='LIMITE')return p.limit?('LIMITE DE '+p.limit+' POR CPF'):'';if(role==='PRECO_APP')return p.app?('R$ '+p.app):'';return''};
function css(){if(document.getElementById('sr15-css'))return;const s=document.createElement('style');s.id='sr15-css';s.textContent=`.pro-part{position:absolute;box-sizing:border-box}.part-edit-mode .pro-part{cursor:move}.pro-part.part-selected{outline:2px dashed #00a2ff;outline-offset:2px}.pro-part.part-locked{cursor:not-allowed!important}.part-handle{position:absolute;width:10px;height:10px;right:-5px;bottom:-5px;border:2px solid #fff;background:#00a2ff;border-radius:2px;cursor:nwse-resize;z-index:120}.pro-guide{position:absolute;pointer-events:none;background:#00a2ff;z-index:150}.pro-guide.v{top:0;bottom:0;width:1px}.pro-guide.h{left:0;right:0;height:1px}.pro-toolbar{display:flex;gap:6px;flex-wrap:wrap;margin:8px 0}.pro-toolbar button.active{background:#9b5cff;color:#fff;border-color:#9b5cff}.layer-row{display:grid;grid-template-columns:1fr auto auto auto;gap:4px;align-items:center;padding:5px 0;border-bottom:1px solid #e9edf4}.layer-row button{padding:4px 6px}.part-metrics{display:grid;grid-template-columns:1fr 1fr;gap:6px}.part-metrics label{font-size:10px;font-weight:800;color:#6b7280}.part-metrics input,.part-metrics select{width:100%;box-sizing:border-box;padding:6px;border:1px solid #d9dfeb;border-radius:6px}.model-badge{display:inline-block;padding:4px 7px;background:#efe9ff;color:#5a2aa8;border-radius:999px;font-size:10px;font-weight:900}.compare-original .slot-outline,.compare-original .slot-empty{display:none!important}@media print{.part-handle,.pro-guide{display:none!important}.pro-part.part-selected{outline:none!important}}`;document.head.appendChild(s)}css();
function styleText(n,s={},role){n.style.fontFamily=s.font||'Segoe UI';n.style.fontWeight=s.bold?'900':'700';n.style.fontStyle=s.italic?'italic':'normal';n.style.color=s.color||'#172033';const a=s.align||'center';n.style.textAlign=a;n.style.justifyContent=a==='right'?'flex-end':a==='left'?'flex-start':'center';const v=s.vAlign||'center';n.style.alignItems=v==='top'?'flex-start':v==='bottom'?'flex-end':'center';n.style.lineHeight=role==='NOME'?'1.02':'1';n.style.padding=role==='NOME'?'1px 3px':'1px';n.style.overflow='hidden';n.style.boxSizing='border-box'}
function fitText(n,role,f){const s=f.style||{},manual=Number(s.fontSize||0),base=manual||20;let min,max;if(role==='NOME'){min=Math.max(6,base*.38);max=Math.max(base,Math.min(base*1.25,f.h*.95));n.style.whiteSpace='normal';n.style.overflowWrap='break-word'}else{min=Math.max(6,base*.45);max=Math.max(base,Math.min(base*1.35,f.h*1.12));n.style.whiteSpace='nowrap'}let lo=min,hi=max,best=min;for(let i=0;i<14;i++){const m=(lo+hi)/2;n.style.fontSize=m+'px';if(n.scrollWidth<=n.clientWidth+1&&n.scrollHeight<=n.clientHeight+1){best=m;lo=m}else hi=m}n.style.fontSize=best+'px'}
function guide(kind,v){const g=E('div','pro-guide '+kind);if(kind==='v')g.style.left=v+'px';else g.style.top=v+'px';A.pageNode.appendChild(g);return g}
function snapAxis(start,size,cands,th=6){let best={delta:0,line:null,d:th+1};for(const c of cands){for(const p of [start,start+size/2,start+size]){const d=Math.abs(c-p);if(d<best.d){best={delta:c-p,line:c,d}}}}return best.d<=th?best:{delta:0,line:null}}
function candidates(pg,e,role){const xs=[0,pg.width/2,pg.width],ys=[0,pg.height/2,pg.height];for(const other of pg.elements||[]){if(!other.slotId)continue;const slot=(pg.templateSlots||[]).find(s=>s.id===other.slotId);if(!slot)continue;for(const [r,b] of Object.entries(slot.fields||{})){if(other.id===e.id&&r===role)continue;const f=A.effectiveField(other,r,b);xs.push(f.x,f.x+f.w/2,f.x+f.w);ys.push(f.y,f.y+f.h/2,f.y+f.h)}}return{xs,ys}}
function bindPart(node,e,role,base,pg){if(!A.state.partEditMode)return;const edit=A.ensurePart(e,role);node.style.pointerEvents='auto';node.classList.toggle('part-locked',Boolean(edit.locked));node.addEventListener('pointerdown',ev=>{if(ev.button!==0||ev.target.classList.contains('part-handle'))return;ev.stopPropagation();A.state.selected=e.id;A.state.selectedPart=role;if(edit.locked){A.emit();return}A.snapshot();let sx=ev.clientX,sy=ev.clientY,ox=Number(edit.dx)||0,oy=Number(edit.dy)||0;const scale=Number(A.state.zoom)||1,c=candidates(pg,e,role);node.setPointerCapture(ev.pointerId);let guides=[];const move=mv=>{let dx=ox+(mv.clientX-sx)/scale,dy=oy+(mv.clientY-sy)/scale;let f=A.effectiveField({...e,partEdits:{...e.partEdits,[role]:{...edit,dx,dy}}},role,base);guides.forEach(g=>g.remove());guides=[];const xs=snapAxis(f.x,f.w,c.xs),ys=snapAxis(f.y,f.h,c.ys);dx+=xs.delta;dy+=ys.delta;if(A.state.snap){dx=Math.round(dx);dy=Math.round(dy)}edit.dx=dx;edit.dy=dy;f=A.effectiveField(e,role,base);node.style.left=f.x+'px';node.style.top=f.y+'px';if(xs.line!==null)guides.push(guide('v',xs.line));if(ys.line!==null)guides.push(guide('h',ys.line))};const up=()=>{node.removeEventListener('pointermove',move);node.removeEventListener('pointerup',up);guides.forEach(g=>g.remove());A.save();A.emit()};node.addEventListener('pointermove',move);node.addEventListener('pointerup',up);A.renderInspector?.()});if(A.state.selected===e.id&&A.state.selectedPart===role&&!edit.locked){const h=E('span','part-handle');node.appendChild(h);h.addEventListener('pointerdown',ev=>{ev.stopPropagation();A.snapshot();let sx=ev.clientX,sy=ev.clientY,ow=Number(edit.dw)||0,oh=Number(edit.dh)||0;const scale=Number(A.state.zoom)||1;h.setPointerCapture(ev.pointerId);const mv=m=>{edit.dw=Math.max(-(base.w-12),ow+(m.clientX-sx)/scale);edit.dh=Math.max(-(base.h-12),oh+(m.clientY-sy)/scale);const f=A.effectiveField(e,role,base);node.style.width=f.w+'px';node.style.height=f.h+'px';if(role!=='IMAGEM')fitText(node,role,f)};const up=()=>{h.removeEventListener('pointermove',mv);h.removeEventListener('pointerup',up);A.save();A.emit()};h.addEventListener('pointermove',mv);h.addEventListener('pointerup',up)})}}
function imageSafe(slot,e,f){const eff=A.effectiveField(e,'IMAGEM',f),px=Math.max(2,eff.w*.035),py=Math.max(2,eff.h*.035);let b={...eff,x:eff.x+px,y:eff.y+py,w:Math.max(16,eff.w-px*2),h:Math.max(16,eff.h-py*2)};for(const r of ['PRECO_REAIS','PRECO_CENTAVOS','PRECO_RS','UNIDADE']){const q0=slot.fields?.[r];if(!q0)continue;const q=A.effectiveField(e,r,q0);const ix=Math.max(0,Math.min(b.x+b.w,q.x+q.w)-Math.max(b.x,q.x)),iy=Math.max(0,Math.min(b.y+b.h,q.y+q.h)-Math.max(b.y,q.y));if(ix*iy<=0)continue;if(q.x>b.x+b.w/2)b.w=Math.max(16,q.x-b.x-3);else if(q.y>b.y+b.h/2)b.h=Math.max(16,q.y-b.y-3)}return b}
function addImage(pg,slot,e,p,base){if(!p.image)return;const b=imageSafe(slot,e,base),edit=A.ensurePart(e,'IMAGEM'),wrap=E('div','pro-part image-part'+(A.state.selected===e.id&&A.state.selectedPart==='IMAGEM'?' part-selected':''));wrap.dataset.role='IMAGEM';wrap.style.overflow='hidden';wrap.style.zIndex=String(edit.z??8);wrap.style.borderRadius=base.autoDetected?Math.min(24,Math.max(7,Math.min(b.w,b.h)*.10))+'px':'0';pos(wrap,b);const img=E('img');img.src=p.image;img.alt=p.name||'Produto';img.style.width='100%';img.style.height='100%';img.style.objectFit=edit.fit||base.fit||base.style?.fit||'contain';img.style.objectPosition=(edit.focusX??50)+'% '+(edit.focusY??50)+'%';img.style.transform='scale('+(Number(edit.imageScale)||1)+')';img.style.transformOrigin=img.style.objectPosition;img.style.display='block';wrap.appendChild(img);A.pageNode.appendChild(wrap);bindPart(wrap,e,'IMAGEM',base,pg)}
function addText(pg,e,p,role,base){const f=A.effectiveField(e,role,base),edit=A.ensurePart(e,role),n=E('div','pro-part text slot-field'+(A.state.selected===e.id&&A.state.selectedPart===role?' part-selected':''),value(role,p));n.dataset.role=role;n.style.zIndex=String(edit.z??45);styleText(n,f.style,role);pos(n,f);A.pageNode.appendChild(n);fitText(n,role,f);bindPart(n,e,role,base,pg);if(document.fonts?.ready)document.fonts.ready.then(()=>fitText(n,role,A.effectiveField(e,role,base)))}
function renderTemplate(pg){const bg=E('img','tpl-img');bg.src=pg.backgroundUrl;bg.alt='Design original do Canva';bg.style.objectFit='fill';bg.style.pointerEvents='none';bg.style.zIndex='1';pos(bg,{x:0,y:0,w:pg.width,h:pg.height});A.pageNode.appendChild(bg)}
function renderSlot(pg,e,p,slot){if(slot.fields?.IMAGEM)addImage(pg,slot,e,p,slot.fields.IMAGEM);for(const r of ['NOME','PRECO_RS','PRECO_REAIS','PRECO_CENTAVOS','UNIDADE','LIMITE','PRECO_APP'])if(slot.fields?.[r])addText(pg,e,p,r,slot.fields[r]);const out=E('div','slot-outline'+(A.state.selected===e.id?' selected':''));out.style.zIndex='80';out.style.pointerEvents=A.state.partEditMode?'none':'auto';pos(out,slot);out.addEventListener('click',ev=>{ev.stopPropagation();A.state.selected=e.id;A.state.selectedPart=null;A.emit()});A.pageNode.appendChild(out)}
A.renderCanvas=()=>{const pg=A.page();if(!pg?.backgroundUrl)return previous();A.pageNode.replaceChildren();A.pageNode.classList.toggle('part-edit-mode',A.state.partEditMode);A.pageNode.classList.toggle('compare-original',A.state.compareOriginal);A.pageNode.style.width=pg.width+'px';A.pageNode.style.height=pg.height+'px';A.zoomNode.style.transform='scale('+A.state.zoom+')';A.zoomNode.style.marginBottom='-'+(pg.height*(1-A.state.zoom))+'px';renderTemplate(pg);if(A.state.compareOriginal)return;const filled=new Map((pg.elements||[]).filter(e=>e.slotId).map(e=>[e.slotId,e]));for(const s of pg.templateSlots||[])if(!filled.has(s.id)){const x=E('div','slot-empty','PRODUTO '+s.index);x.style.zIndex='70';pos(x,s);A.pageNode.appendChild(x)}for(const e of pg.elements||[]){const p=A.state.products.find(x=>x.id===e.productId);if(!p)continue;const s=(pg.templateSlots||[]).find(x=>x.id===e.slotId);if(s)renderSlot(pg,e,p,s);else{return previous()}}};
console.info('[SR Studio] Beta 15 editor manual por partes ativo');
})();

(() => {
'use strict';
const A=window.SR11,E=A.E;if(!A||A.__BETA15_TOOLS__)return;A.__BETA15_TOOLS__=true;
function button(label,fn,cls='btn'){const b=E('button',cls,label);b.type='button';b.addEventListener('click',fn);return b}
function field(label,value,onchange,type='number'){const wrap=E('label');wrap.style.fontSize='10px';wrap.style.fontWeight='800';wrap.textContent=label;const i=E('input','input');i.type=type;i.value=value??'';i.addEventListener('change',()=>onchange(i.value));wrap.appendChild(i);return wrap}
function select(label,value,items,onchange){const wrap=E('label');wrap.style.fontSize='10px';wrap.style.fontWeight='800';wrap.textContent=label;const s=E('select','input');for(const [v,t] of items){const o=E('option','',t);o.value=v;if(String(v)===String(value))o.selected=true;s.appendChild(o)}s.addEventListener('change',()=>onchange(s.value));wrap.appendChild(s);return wrap}
function selectedContext(){const pg=A.page(),e=A.selectedElement(),slot=A.selectedSlot(),p=e&&A.state.products.find(x=>x.id===e.productId);return{pg,e,slot,p}}
function setPart(role,patch){const {e}=selectedContext();if(!e||!role)return;A.snapshot();Object.assign(A.ensurePart(e,role),patch);A.state.selectedPart=role;A.commit()}
function addTopControls(){const top=document.querySelector('.top');if(!top||document.getElementById('sr15-edit'))return;const spacer=top.querySelector('.spacer');const edit=button('✥ Editar partes',()=>{A.state.partEditMode=!A.state.partEditMode;if(!A.state.partEditMode)A.state.selectedPart=null;A.save();A.emit();sync()},'');edit.id='sr15-edit';const original=button('◐ Original',()=>{A.state.compareOriginal=!A.state.compareOriginal;A.save();A.renderCanvas();sync()},'');original.id='sr15-original';const learn=button('◆ Aprender modelo',()=>A.learnTemplate(),'');learn.id='sr15-learn';const fill=button('Preencher página',()=>A.fillCurrentPage(),'');fill.id='sr15-fill';for(const b of [edit,original,learn,fill])top.insertBefore(b,spacer);function sync(){edit.classList.toggle('active',A.state.partEditMode);original.classList.toggle('active',A.state.compareOriginal)}sync()}
function appendGeneralTools(host){const {pg,e,slot}=selectedContext(),bar=E('div','pro-toolbar');bar.append(button(A.state.partEditMode?'✓ Editando partes':'Editar partes',()=>{A.state.partEditMode=!A.state.partEditMode;A.save();A.emit()}),button('Original / preenchido',()=>{A.state.compareOriginal=!A.state.compareOriginal;A.save();A.renderCanvas()}),button('Aprender este modelo',()=>A.learnTemplate()),button('Aplicar modelo salvo',()=>A.applyTemplateMemory()),button('Preencher página',()=>A.fillCurrentPage()));host.appendChild(E('div','title','Modo profissional'));host.appendChild(bar);if(pg?.templateSlots?.length)host.appendChild(E('span','model-badge','Template '+A.templateKey(pg).slice(-6).toUpperCase()+(slot?' · bloco '+A.slotType(pg,slot):'')));if(e){const reset=E('div','pro-toolbar');reset.append(button('Resetar produto',()=>A.resetSelectedProduct()),button('Resetar página',()=>A.resetCurrentPage()));host.appendChild(reset)}}
function appendReplace(host){const {e,p}=selectedContext();if(!e||!p)return;host.appendChild(E('div','title','Trocar produto mantendo o bloco'));const s=E('select','input');for(const x of A.state.products){const o=E('option','',x.name||'SEM NOME');o.value=x.id;if(x.id===p.id)o.selected=true;s.appendChild(o)}const b=button('Trocar produto',()=>{if(A.replaceSelectedProduct(s.value))A.toast('Produto substituído mantendo os ajustes.');});host.append(s,b)}
function appendPartEditor(host){const {pg,e,slot}=selectedContext();if(!e||!slot)return;const roles=A.availableParts();if(!roles.length)return;if(!roles.includes(A.state.selectedPart))A.state.selectedPart=roles[0];const role=A.state.selectedPart,base=slot.fields[role],m=A.ensurePart(e,role),eff=A.effectiveField(e,role,base);host.appendChild(E('div','title','Editar parte'));const choose=E('select','input');for(const r of roles){const o=E('option','',A.partLabel(r));o.value=r;if(r===role)o.selected=true;choose.appendChild(o)}choose.addEventListener('change',()=>{A.state.selectedPart=choose.value;A.save();A.emit()});host.appendChild(choose);
const metrics=E('div','part-metrics');metrics.append(field('Mover X',Math.round(m.dx||0),v=>setPart(role,{dx:Number(v)||0})),field('Mover Y',Math.round(m.dy||0),v=>setPart(role,{dy:Number(v)||0})),field('Largura Δ',Math.round(m.dw||0),v=>setPart(role,{dw:Number(v)||0})),field('Altura Δ',Math.round(m.dh||0),v=>setPart(role,{dh:Number(v)||0})));host.appendChild(metrics);
if(role==='IMAGEM'){const row=E('div','part-metrics');row.append(select('Encaixe',m.fit||base.fit||base.style?.fit||'contain',[['contain','Mostrar inteira'],['cover','Preencher caixa'],['fill','Esticar']],v=>setPart(role,{fit:v})),field('Zoom imagem',m.imageScale??1,v=>setPart(role,{imageScale:Math.max(.2,Math.min(4,Number(v)||1))})));host.appendChild(row);const focus=E('div','part-metrics');focus.append(field('Foco X %',m.focusX??50,v=>setPart(role,{focusX:Math.max(0,Math.min(100,Number(v)||50))})),field('Foco Y %',m.focusY??50,v=>setPart(role,{focusY:Math.max(0,Math.min(100,Number(v)||50))})));host.appendChild(focus)}else{const row=E('div','part-metrics');row.append(field('Fonte',m.fontSize??base.style?.fontSize??'',v=>setPart(role,{fontSize:Number(v)||undefined})),select('Alinhamento',m.align||base.style?.align||'center',[['left','Esquerda'],['center','Centro'],['right','Direita']],v=>setPart(role,{align:v})));host.appendChild(row)}
const lock=E('label');lock.style.display='flex';lock.style.gap='6px';lock.style.alignItems='center';const chk=E('input');chk.type='checkbox';chk.checked=Boolean(m.locked);chk.addEventListener('change',()=>setPart(role,{locked:chk.checked}));lock.append(chk,E('span','',chk.checked?'Parte bloqueada':'Bloquear esta parte'));host.appendChild(lock);
const actions=E('div','pro-toolbar');actions.append(button('Resetar parte',()=>A.resetSelectedPart()),button('Copiar parte → semelhantes',()=>A.copyPartToSimilar()),button('Copiar produto → semelhantes',()=>A.copyProductAdjustmentsToSimilar()));host.appendChild(actions);host.appendChild(E('div','help','Arraste diretamente no encarte para mover. Use o quadradinho azul para redimensionar. Setas movem 1 px; Shift + seta move 10 px.'));
host.appendChild(E('div','title','Camadas do produto'));for(const r of roles){const mm=A.ensurePart(e,r),row=E('div','layer-row');const name=button((A.state.selectedPart===r?'● ':'')+A.partLabel(r),()=>{A.state.selectedPart=r;A.emit()},'btn');const back=button('↓',()=>setPart(r,{z:(Number(mm.z)||(r==='IMAGEM'?8:45))-5}),'btn');const front=button('↑',()=>setPart(r,{z:(Number(mm.z)||(r==='IMAGEM'?8:45))+5}),'btn');const lockb=button(mm.locked?'🔒':'🔓',()=>setPart(r,{locked:!mm.locked}),'btn');row.append(name,back,front,lockb);host.appendChild(row)}host.appendChild(E('div','help','Posição atual: X '+Math.round(eff.x)+' · Y '+Math.round(eff.y)+' · '+Math.round(eff.w)+'×'+Math.round(eff.h)+' px'))}
const oldInspector=A.renderInspector;A.renderInspector=()=>{oldInspector();appendGeneralTools(A.inspectorNode);appendPartEditor(A.inspectorNode);appendReplace(A.inspectorNode)};
addTopControls();
document.addEventListener('keydown',ev=>{if(!A.state.partEditMode||!A.state.selectedPart||['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName))return;const map={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]};if(!map[ev.key])return;const e=A.selectedElement(),role=A.state.selectedPart;if(!e||A.ensurePart(e,role).locked)return;ev.preventDefault();const k=ev.shiftKey?10:1,[dx,dy]=map[ev.key];A.snapshot();const m=A.ensurePart(e,role);m.dx=(Number(m.dx)||0)+dx*k;m.dy=(Number(m.dy)||0)+dy*k;A.commit()});
A.emit();
console.info('[SR Studio] Beta 15 ferramentas PRO ativas');
})();

(() => {
'use strict';
const A=window.SR11,E=A.E;if(!A||A.__BETA15_PROJECT__)return;A.__BETA15_PROJECT__=true;
A.VERSION_STORE='srstudio_encartes_named_versions_v1';
const readVersions=()=>{try{return JSON.parse(localStorage.getItem(A.VERSION_STORE)||'[]')||[]}catch{return[]}};
const writeVersions=v=>{try{localStorage.setItem(A.VERSION_STORE,JSON.stringify(v.slice(0,12)))}catch{}};
A.saveNamedVersion=name=>{const list=readVersions(),label=(name||'').trim()||('Versão '+new Date().toLocaleString('pt-BR'));list.unshift({id:A.uid('ver'),name:label,at:new Date().toISOString(),state:A.copy(A.state)});writeVersions(list);A.toast('Versão salva: '+label);return label};
A.restoreNamedVersion=id=>{const item=readVersions().find(x=>x.id===id);if(!item)return false;A.snapshot();A.state=A.copy(item.state);A.commit();A.toast('Versão restaurada: '+item.name);return true};
A.exportProject=()=>{const payload={format:'SR_STUDIO_ENCARTES_PROJECT_1',savedAt:new Date().toISOString(),version:A.VERSION,state:A.state,templateMemory:A.loadTemplateMemory()};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(A.state.projectName||'encarte').replace(/[^a-z0-9_-]+/gi,'_')+'.srstudio.json';document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},500);A.toast('Backup do projeto exportado.')};
A.importProject=async file=>{const data=JSON.parse(await file.text());if(data?.format!=='SR_STUDIO_ENCARTES_PROJECT_1'||!data.state?.pages||!data.state?.products)throw Error('Arquivo de projeto inválido.');A.snapshot();A.state=data.state;if(data.templateMemory)A.saveTemplateMemory(data.templateMemory);A.commit();A.toast('Projeto restaurado com sucesso.')};
function modal(){const bg=E('div','modal-bg'),box=E('div','modal');box.appendChild(E('h2','','Versões do projeto'));const name=E('input','input');name.placeholder='Nome da versão (ex.: Quinta Filé aprovado)';const save=E('button','btn','Salvar versão atual');save.addEventListener('click',()=>{A.saveNamedVersion(name.value);bg.remove()});box.append(name,save,E('div','title','Versões salvas'));const list=readVersions();if(!list.length)box.appendChild(E('div','help','Nenhuma versão manual salva ainda.'));for(const v of list){const row=E('div','layer-row'),info=E('div');info.append(E('b','',v.name),E('div','help',new Date(v.at).toLocaleString('pt-BR')));const restore=E('button','btn','Restaurar');restore.addEventListener('click',()=>{if(confirm('Restaurar esta versão?')){A.restoreNamedVersion(v.id);bg.remove()}});const del=E('button','btn danger','Excluir');del.addEventListener('click',()=>{writeVersions(readVersions().filter(x=>x.id!==v.id));bg.remove();modal()});row.style.gridTemplateColumns='1fr auto auto';row.append(info,restore,del);box.appendChild(row)}const close=E('button','btn','Fechar');close.addEventListener('click',()=>bg.remove());box.appendChild(close);bg.appendChild(box);document.body.appendChild(bg)}
function install(){const top=document.querySelector('.top'),spacer=top?.querySelector('.spacer');if(!top||!spacer||document.getElementById('sr15-backup'))return;const backup=E('button');backup.id='sr15-backup';backup.textContent='Backup';backup.addEventListener('click',A.exportProject);const versions=E('button');versions.textContent='Versões';versions.addEventListener('click',modal);const inp=E('input','file');inp.type='file';inp.accept='.json,.srstudio.json';inp.style.display='none';inp.addEventListener('change',async()=>{try{if(inp.files[0])await A.importProject(inp.files[0])}catch(e){A.toast(e.message||'Falha ao abrir projeto')}finally{inp.value=''}});const open=E('button');open.textContent='Abrir projeto';open.addEventListener('click',()=>inp.click());top.insertBefore(backup,spacer);top.insertBefore(versions,spacer);top.insertBefore(open,spacer);top.appendChild(inp)}install();
console.info('[SR Studio] Beta 15 backup e versões ativos');
})();
