(() => {
'use strict';
const A=window.SR11;if(!A||A.__SR5_PROJECT_BRIDGE__)return;A.__SR5_PROJECT_BRIDGE__=true;
const params=new URLSearchParams(location.search),projectId=(params.get('v5project')||'').trim(),captureMode=params.get('v5capture')==='1',capturePage=Math.max(0,Number(params.get('exportPage'))||0);
A.VERSION='5.0.0 • Next';const ver=document.querySelector('.ver');if(ver)ver.textContent=A.VERSION;
if(!projectId){console.info('[SR Studio 5] Editor aberto sem projeto persistente.');return}
A.v5ProjectId=projectId;A.v5Project=null;A.v5Loading=true;A.v5Saving=false;A.v5SaveTimer=null;A.v5LastSaved='';A.v5SaveStatus='Carregando projeto...';
let statusNode=null,saveBtn=null,versionBtn=null;
function css(){if(document.getElementById('sr5-project-css'))return;const s=document.createElement('style');s.id='sr5-project-css';s.textContent=`.sr5-project-pill{display:flex;align-items:center;gap:6px;height:30px;padding:0 9px;border:1px solid #d9dfeb;border-radius:7px;background:#f8fafc;color:#475467;font:700 11px system-ui;white-space:nowrap}.sr5-project-pill.saving{color:#7c3aed;border-color:#c4b5fd;background:#f5f3ff}.sr5-project-pill.ok{color:#18794e;border-color:#a7e3c3;background:#f0fdf4}.sr5-project-pill.error{color:#b42318;border-color:#f5b7b1;background:#fff5f4}.sr5-project-btn{height:32px;border:1px solid #d8dce7;border-radius:7px;background:#fff;padding:0 10px;font:700 11px system-ui;cursor:pointer}.sr5-project-btn.primary{background:#0b2f6b;color:#fff;border-color:#0b2f6b}.sr5-project-btn:hover{filter:brightness(.98)}`;document.head.appendChild(s)}css();
function setStatus(text,kind=''){A.v5SaveStatus=text;if(statusNode){statusNode.textContent=text;statusNode.className='sr5-project-pill '+kind}}
function ensureToolbar(){if(captureMode)return;if(statusNode&&statusNode.isConnected)return;const top=document.querySelector('.top');if(!top)return setTimeout(ensureToolbar,150);const spacer=top.querySelector('.spacer');statusNode=document.createElement('span');statusNode.className='sr5-project-pill';statusNode.textContent=A.v5SaveStatus;saveBtn=document.createElement('button');saveBtn.className='sr5-project-btn primary';saveBtn.textContent='Salvar projeto';saveBtn.title='Salvar projeto no SR Studio 5.0 (Ctrl+S)';saveBtn.addEventListener('click',()=>save(false));versionBtn=document.createElement('button');versionBtn.className='sr5-project-btn';versionBtn.textContent='Salvar versão';versionBtn.title='Criar uma versão recuperável do projeto';versionBtn.addEventListener('click',createVersion);if(spacer){top.insertBefore(statusNode,spacer);top.insertBefore(versionBtn,spacer);top.insertBefore(saveBtn,spacer)}else top.append(statusNode,versionBtn,saveBtn)}
async function request(url,opts={}){const r=await fetch(url,opts),d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw Error(d.error||('Falha HTTP '+r.status));return d}
function normalizeState(state){const s=state&&typeof state==='object'?state:{};s.products=Array.isArray(s.products)?s.products:[];s.pages=Array.isArray(s.pages)&&s.pages.length?s.pages:[A.newPage?.('Página 1')||{id:'pg1',name:'Página 1',width:794,height:1123,elements:[],templateElements:[],templateSlots:[]}];s.pageIndex=Math.max(0,Math.min(Number(s.pageIndex)||0,s.pages.length-1));s.selected=s.selected||null;s.grid=s.grid!==false;s.snap=s.snap!==false;s.zoom=Number(s.zoom)||.75;s.categoryFilter=s.categoryFilter||'TODAS';s.fonts=Array.isArray(s.fonts)?s.fonts:[];s.projectName=s.projectName||'Projeto SR Studio';s.partEditMode=true;s.proSelection=Array.isArray(s.proSelection)?s.proSelection:[];s.cropKey=s.cropKey||null;s.proGroups=s.proGroups&&typeof s.proGroups==='object'?s.proGroups:{};return s}
function captureCleanPage(){if(!captureMode||!A.pageNode)return;try{const pg=A.page(),clone=A.pageNode.cloneNode(true);clone.querySelectorAll('.sr16-selection,.sr16-guide,.sr16-marquee,.sr16-crop-badge,.slot-outline,.slot-empty,.selected,.pro-guide,.part-handle,.sr16-toolbar').forEach(n=>n.remove());clone.classList.remove('grid','part-edit-mode','sr16-crop');clone.style.position='absolute';clone.style.left='0';clone.style.top='0';clone.style.margin='0';clone.style.transform='none';clone.style.transformOrigin='top left';clone.style.boxShadow='none';clone.style.border='0';clone.style.width=Number(pg.width||794)+'px';clone.style.height=Number(pg.height||1123)+'px';document.documentElement.style.margin='0';document.documentElement.style.padding='0';document.documentElement.style.width=Number(pg.width||794)+'px';document.documentElement.style.height=Number(pg.height||1123)+'px';document.documentElement.style.overflow='hidden';document.body.replaceChildren(clone);document.body.style.margin='0';document.body.style.padding='0';document.body.style.width=Number(pg.width||794)+'px';document.body.style.height=Number(pg.height||1123)+'px';document.body.style.overflow='hidden';document.body.style.background='#fff';document.title='SR Studio Capture Ready'}catch(e){console.error('[SR Studio 5] Falha no modo captura',e)}}
async function loadProject(){ensureToolbar();setStatus('Carregando projeto...','saving');try{const d=await request('/api/v5/project?id='+encodeURIComponent(projectId));A.v5Project=d.project||null;A.state=normalizeState(d.state);A.past=[];A.future=[];if(captureMode){A.state.pageIndex=Math.min(capturePage,A.state.pages.length-1);A.state.selected=null;A.state.proSelection=[];A.state.cropKey=null;A.state.grid=false;A.state.snap=false;A.state.zoom=1}else A.save?.();A.v5Loading=false;A.v5LastSaved=new Date().toISOString();setStatus('Projeto carregado','ok');A.emit?.();if(captureMode){setTimeout(()=>{A.renderCanvas?.();setTimeout(captureCleanPage,450)},250)}else setTimeout(()=>setStatus('Salvo','ok'),1200);console.info('[SR Studio 5] Projeto carregado:',projectId)}catch(e){A.v5Loading=false;setStatus('Erro ao carregar','error');if(!captureMode)A.toast?.(e.message||'Falha ao carregar projeto');console.error(e)}}
function scheduleAutosave(){if(captureMode||A.v5Loading||A.v5Saving)return;clearTimeout(A.v5SaveTimer);setStatus('Alterações pendentes','');A.v5SaveTimer=setTimeout(()=>save(true),1200)}
async function save(autosave=true){if(captureMode||A.v5Loading||A.v5Saving)return false;clearTimeout(A.v5SaveTimer);A.v5Saving=true;setStatus(autosave?'Salvando automaticamente...':'Salvando projeto...','saving');try{const d=await request('/api/v5/project/save?id='+encodeURIComponent(projectId)+'&autosave='+(autosave?'1':'0'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({state:A.state})});A.v5LastSaved=d.saved_at||new Date().toISOString();setStatus(autosave?'Autosave concluído':'Projeto salvo','ok');if(!autosave)A.toast?.('Projeto salvo no SR Studio 5.0.');setTimeout(()=>{if(!A.v5Saving)setStatus('Salvo','ok')},1400);return true}catch(e){setStatus('Falha ao salvar','error');if(!autosave)A.toast?.(e.message||'Falha ao salvar projeto');console.error(e);return false}finally{A.v5Saving=false}}
async function createVersion(){const label=prompt('Nome da versão:','Versão '+new Date().toLocaleString('pt-BR'));if(label===null)return;await save(false);try{await request('/api/v5/project/snapshot?id='+encodeURIComponent(projectId),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({label:label||'Versão manual'})});A.toast?.('Versão do projeto salva.')}catch(e){A.toast?.(e.message||'Falha ao criar versão')}}
A.onChange?.(()=>scheduleAutosave());
document.addEventListener('keydown',ev=>{if(captureMode)return;const ctrl=ev.ctrlKey||ev.metaKey;if(ctrl&&ev.key.toLowerCase()==='s'){ev.preventDefault();ev.stopImmediatePropagation();save(false)}},true);
window.addEventListener('beforeunload',()=>{if(captureMode||A.v5Loading)return;try{clearTimeout(A.v5SaveTimer);const blob=new Blob([JSON.stringify({state:A.state})],{type:'application/json'});navigator.sendBeacon('/api/v5/project/save?id='+encodeURIComponent(projectId)+'&autosave=1',blob)}catch{}});
ensureToolbar();loadProject();
console.info('[SR Studio 5] Bridge de projetos/autosave ativo.',captureMode?'modo captura':'modo edição');
})();
