from __future__ import annotations

"""Resolve a ordem lógica dos slides de um pacote PPTX.

Os nomes ``slide1.xml``, ``slide2.xml`` etc. são nomes de partes OPC e não são
um contrato de ordem de apresentação. PowerPoint preserva a ordem editável em
``p:presentation/p:sldIdLst``; cada entrada aponta por relacionamento para a
parte de slide correspondente.

O helper é deliberadamente tolerante: arquivos incompletos ou fixtures mínimos
continuam funcionando pela ordem numérica histórica, e partes de slide órfãs são
anexadas ao final em vez de desaparecerem silenciosamente.
"""

import posixpath
import re
import zipfile
from xml.etree import ElementTree as ET

P_NS = "http://schemas.openxmlformats.org/presentationml/2006/main"
R_NS = "http://schemas.openxmlformats.org/officeDocument/2006/relationships"
PKG_REL_NS = "http://schemas.openxmlformats.org/package/2006/relationships"

_PRESENTATION = "ppt/presentation.xml"
_PRESENTATION_RELS = "ppt/_rels/presentation.xml.rels"
_SLIDE_RE = re.compile(r"^ppt/slides/slide(\d+)\.xml$")


def ordered_slide_paths(archive: zipfile.ZipFile) -> list[str]:
    """Return slide part paths in PowerPoint presentation order.

    Falls back to numeric part order when presentation relationships are absent
    or malformed. Any valid slide part not referenced by ``sldIdLst`` is appended
    deterministically so import never drops content merely because the package is
    partially repaired or generated by a non-Office producer.
    """

    available = [name for name in archive.namelist() if _SLIDE_RE.fullmatch(name)]
    numeric = sorted(available, key=_slide_number)
    if not numeric:
        return []

    try:
        presentation = ET.fromstring(archive.read(_PRESENTATION))
        relationships = ET.fromstring(archive.read(_PRESENTATION_RELS))
    except (KeyError, ET.ParseError):
        return numeric

    targets: dict[str, str] = {}
    for relationship in relationships.findall(f"{{{PKG_REL_NS}}}Relationship"):
        rel_id = str(relationship.get("Id") or "")
        target = str(relationship.get("Target") or "")
        if not rel_id or not target:
            continue
        normalized = _normalize_presentation_target(target)
        if normalized:
            targets[rel_id] = normalized

    ordered: list[str] = []
    seen: set[str] = set()
    for slide_id in presentation.findall(f".//{{{P_NS}}}sldId"):
        rel_id = str(slide_id.get(f"{{{R_NS}}}id") or "")
        target = targets.get(rel_id, "")
        if target in available and target not in seen:
            ordered.append(target)
            seen.add(target)

    if not ordered:
        return numeric
    ordered.extend(path for path in numeric if path not in seen)
    return ordered


def _normalize_presentation_target(target: str) -> str:
    raw = str(target or "").replace("\\", "/").strip()
    if not raw:
        return ""
    if raw.startswith("/"):
        return posixpath.normpath(raw.lstrip("/"))
    return posixpath.normpath(posixpath.join("ppt", raw))


def _slide_number(path: str) -> int:
    match = _SLIDE_RE.fullmatch(path)
    return int(match.group(1)) if match else 0
