(() => {
'use strict';
const A=window.SR11;
A.pick=(row,names)=>{const m={};Object.keys(row||{}).forEach(k=>m[A.norm(k)]=row[k]);for(const n of names){const v=m[A.norm(n)];if(v!==undefined&&v!==null&&String(v).trim()!=='')return v}return''};
A.detectUnit=row=>{let u=A.pick(row,['UNIDADE','UN','UND','UN VENDA']);if(u)return A.norm(u).slice(0,6);const e=A.pick(row,['ENTRADA']);if(typeof e==='string'){const x=A.norm(e);if(x.includes('KG'))return'KG';if(x.includes('UN'))return'UN'}if(typeof e==='number'&&!Number.isInteger(e))return'KG';return''};
A.rowProduct=row=>{const name=A.pick(row,['PRODUTO','PRODUTOS','NOME','DESCRICAO','DESCRIÇÃO','ITEM','DESCRICAO PRODUTO']);const code=A.pick(row,['EAN','CODIGO','CÓDIGO','COD','COD BARRAS','CODIGO DE BARRAS']);const price=A.pick(row,['PRECO PROMOCAO','PREÇO PROMOÇÃO','PROMOCAO','PROMOÇÃO','PRECO','PREÇO','VAREJO']);const app=A.pick(row,['PRECO APP','PREÇO APP','APP','CLUBE','PRECO CLUBE']);const limit=A.pick(row,['LIMITE','LIMITE CPF','LIMITE POR CPF']);if(!name&&!code&&!price)return null;return{id:A.uid('p'),name:String(name||'').trim(),code:String(code||'').trim(),price:A.money(price),app:A.money(app),limit:String(limit||'').trim(),unit:A.detectUnit(row),image:'',category:'SEM CATEGORIA',bankFound:false,matchMethod:''}};
A.headerIndex=rows=>{let best=0,score=-1;for(let i=0;i<Math.min(rows.length,20);i++){let s=0;for(const x of rows[i]||[]){const v=A.norm(x);if(/EAN|CODIGO|COD\b|PRODUTO|DESCRICAO|ITEM|PROMOCAO|PRECO|VENDA|LIMITE|ENTRADA/.test(v))s+=2;if(v)s+=.05}if(s>score){score=s;best=i}}return best};
A.rowsFromSheet=ws=>{const m=XLSX.utils.sheet_to_json(ws,{header:1,defval:''});if(!m.length)return[];const hi=A.headerIndex(m),heads=m[hi].map(x=>String(x||'').trim());return m.slice(hi+1).filter(r=>r.some(x=>String(x||'').trim())).map(r=>{const o={};heads.forEach((h,i)=>{if(h)o[h]=r[i]??''});return o})};
A.resolveBank=async products=>{const response=await fetch('/api/encartes/resolve-products',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({items:products.map(p=>({code:p.code,name:p.name}))})});const data=await response.json();if(!response.ok||!data.ok)throw Error(data.error||'Banco de Produtos indisponível');let found=0;products.forEach((p,i)=>{const x=(data.results||[])[i]||{};if(x.found){found++;p.bankFound=true;p.matchMethod=x.match_method||'';p.identityKey=x.identity_key||'';p.name=x.canonical_name||p.name||('PRODUTO '+p.code);p.unit=p.unit||x.unidade||'UN';p.image=x.image||'';p.code=x.codigo||x.codigo_ciss||p.code;p.category=x.categoria||p.category}else{p.name=p.name||('CÓDIGO '+(p.code||'NÃO IDENTIFICADO'));p.unit=p.unit||'UN'}});return found};
A.importSheet=async file=>{if(!file)return{total:0,found:0};let rows=[];if(/\.csv$|\.txt$/i.test(file.name)){const wb=XLSX.read(await file.text(),{type:'string'});rows=A.rowsFromSheet(wb.Sheets[wb.SheetNames[0]])}else{const wb=XLSX.read(await file.arrayBuffer(),{type:'array'});rows=A.rowsFromSheet(wb.Sheets[wb.SheetNames[0]])}const products=rows.map(A.rowProduct).filter(Boolean);if(!products.length)throw Error('Nenhuma linha de produto reconhecida.');let found=0;try{found=await A.resolveBank(products)}catch(e){console.warn(e);products.forEach(p=>{p.name=p.name||('CÓDIGO '+(p.code||'NÃO IDENTIFICADO'));p.unit=p.unit||'UN'})}A.snapshot();A.state.products.push(...products);A.commit();return{total:products.length,found}};
A.registerFont=async f=>{if(!f?.family||!f?.url)return;try{const face=new FontFace(f.family,'url("'+f.url+'")');document.fonts.add(await face.load())}catch(e){console.warn(e)}};
A.loadFonts=async()=>{try{const r=await fetch('/api/encartes/fonts'),d=await r.json();if(d.ok){A.state.fonts=d.fonts||[];for(const f of A.state.fonts)await A.registerFont(f)}}catch(e){console.warn(e)}return A.state.fonts};
A.importFonts=async files=>{let ok=0;for(const file of [...(files||[])]){const response=await fetch('/api/encartes/font-upload?name='+encodeURIComponent(file.name),{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:await file.arrayBuffer()});const data=await response.json();if(!response.ok||!data.ok)throw Error(data.error||('Falha ao importar '+file.name));A.state.fonts=A.state.fonts.filter(x=>x.name!==data.font.name);A.state.fonts.push(data.font);await A.registerFont(data.font);ok++}A.commit();return ok};
})();
