(() => {
'use strict';
const A=window.SR11,E=A.E;
const sheet=document.getElementById('sheetFile'),pptx=document.getElementById('pptxFile'),fonts=document.getElementById('fontFile'),search=document.getElementById('search'),category=document.getElementById('category'),zoom=document.getElementById('zoom');
const printHost=E('div','print-host');document.body.appendChild(printHost);
function manualProduct(){A.snapshot();A.state.products.push({id:A.uid('p'),name:'NOVO PRODUTO',code:'',price:'0,00',app:'',limit:'',unit:'UN',image:'',category:'SEM CATEGORIA',bankFound:false,matchMethod:'MANUAL'});A.commit()}
function validationModal(){const list=A.validate(),bg=E('div','modal-bg'),box=E('div','modal');box.appendChild(E('h2','',list.length?'Verificação do Encarte':'Encarte validado'));const issues=E('div','issues');if(!list.length)issues.appendChild(E('div','issue ok','Nenhum erro ou aviso encontrado.'));else for(const item of list)issues.appendChild(E('div','issue '+item.severity,item.message));box.appendChild(issues);const actions=E('div','modal-actions'),close=E('button','btn','Fechar');close.addEventListener('click',()=>bg.remove());actions.appendChild(close);box.appendChild(actions);bg.appendChild(box);document.body.appendChild(bg)}
function preparePrint(){const old=A.state.pageIndex;printHost.replaceChildren();for(let i=0;i<A.state.pages.length;i++){A.state.pageIndex=i;A.renderCanvas();const copy=A.pageNode.cloneNode(true);copy.classList.remove('grid');copy.querySelectorAll('.selected,.slot-outline,.slot-empty').forEach(n=>n.remove());printHost.appendChild(copy)}A.state.pageIndex=old;A.renderAll();setTimeout(()=>window.print(),100)}
async function importPptx(file){if(!file)return;A.setStatus('Analisando PPTX do Canva...');const response=await fetch('/api/encartes/import-pptx?name='+encodeURIComponent(file.name),{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:await file.arrayBuffer()});const data=await response.json();if(!response.ok||!data.ok)throw Error(data.error||'Falha ao analisar PPTX');A.snapshot();A.state.pages=(data.pages||[]).map((p,i)=>({...p,id:A.uid('pg'),name:p.name||('Página '+(i+1)),elements:[]}));if(!A.state.pages.length)A.state.pages=[A.newPage('Página 1')];A.state.pageIndex=0;A.state.selected=null;A.commit();A.setStatus('PPTX: '+(data.slotCount||0)+' bloco(s) reconhecido(s)');A.toast((data.pageCount||0)+' página(s) do Canva importada(s)')}
document.addEventListener('click',async ev=>{
  const add=ev.target.closest('[data-product-id]');if(add&&add.classList.contains('prod-add')){A.placeProduct(add.dataset.productId);return}
  const tab=ev.target.closest('[data-page-index]');if(tab){A.state.pageIndex=Number(tab.dataset.pageIndex)||0;A.state.selected=null;A.emit();return}
  const action=ev.target.closest('[data-action]')?.dataset.action;if(!action)return;
  try{
    if(action==='sheet')sheet.click();else if(action==='pptx')pptx.click();else if(action==='fonts')fonts.click();else if(action==='undo')A.undo();else if(action==='redo')A.redo();else if(action==='auto'){const mode=A.autoLayout();A.toast(mode==='template'?'Template preenchido automaticamente':'Produtos organizados por categoria')}else if(action==='validate')validationModal();else if(action==='print')preparePrint();else if(action==='manual')manualProduct();else if(action==='clear'){if(confirm('Limpar produtos e páginas do projeto?')){A.snapshot();A.state.products=[];A.state.pages=[A.newPage('Página 1')];A.state.pageIndex=0;A.state.selected=null;A.commit()}}else if(action==='addPage')A.addPage();else if(action==='dupPage')A.duplicatePage();else if(action==='delPage'){if(!A.deletePage())A.toast('O projeto precisa ter pelo menos uma página.')}else if(action==='dupSelected'){if(!A.duplicateSelected())A.toast('Não há outro bloco livre para duplicar.')}else if(action==='delSelected')A.deleteSelected();
  }catch(e){console.error(e);A.toast(e.message||'Falha na operação')}
});
sheet.addEventListener('change',async()=>{const file=sheet.files[0];if(!file)return;try{A.setStatus('Importando planilha e consultando Banco...');const r=await A.importSheet(file);A.setStatus('Banco: '+r.found+' encontrado(s) · '+(r.total-r.found)+' não localizado(s)');A.toast(r.total+' produto(s) importados')}catch(e){A.toast(e.message);A.setStatus('Falha na planilha')}finally{sheet.value=''}});
pptx.addEventListener('change',async()=>{try{await importPptx(pptx.files[0])}catch(e){A.toast(e.message);A.setStatus('Falha no PPTX')}finally{pptx.value=''}});
fonts.addEventListener('change',async()=>{try{const total=await A.importFonts(fonts.files);A.toast(total+' fonte(s) importada(s) manualmente')}catch(e){A.toast(e.message)}finally{fonts.value=''}});
search.addEventListener('input',A.renderProducts);category.addEventListener('change',()=>{A.state.categoryFilter=category.value;A.renderProducts()});zoom.addEventListener('change',()=>{A.state.zoom=Number(zoom.value)||.75;A.save();A.renderCanvas()});
document.addEventListener('keydown',ev=>{if((ev.ctrlKey||ev.metaKey)&&ev.key.toLowerCase()==='z'){ev.preventDefault();ev.shiftKey?A.redo():A.undo()}else if((ev.ctrlKey||ev.metaKey)&&ev.key.toLowerCase()==='y'){ev.preventDefault();A.redo()}else if(ev.key==='Delete'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName))A.deleteSelected()});
A.loadFonts().then(()=>A.emit());A.renderAll();
})();
