(() => {
'use strict';
const A=window.SR11,E=A.E;
A.printHost=E('div','print-host');document.body.appendChild(A.printHost);
A.addManualProduct=()=>{A.snapshot();A.state.products.push({id:A.uid('p'),name:'NOVO PRODUTO',code:'',price:'0,00',app:'',limit:'',unit:'UN',image:'',category:'SEM CATEGORIA',bankFound:false,matchMethod:'MANUAL'});A.commit()};
A.showValidation=()=>{const list=A.validate(),bg=E('div','modal-bg'),box=E('div','modal');box.appendChild(E('h2','',list.length?'Verificação do Encarte':'Encarte validado'));const issues=E('div','issues');if(!list.length)issues.appendChild(E('div','issue ok','Nenhum erro ou aviso encontrado.'));else for(const item of list)issues.appendChild(E('div','issue '+item.severity,item.message));box.appendChild(issues);const actions=E('div','modal-actions'),close=E('button','btn','Fechar');close.addEventListener('click',()=>bg.remove());actions.appendChild(close);box.appendChild(actions);bg.appendChild(box);document.body.appendChild(bg)};
A.printProject=()=>{const old=A.state.pageIndex;A.printHost.replaceChildren();for(let i=0;i<A.state.pages.length;i++){A.state.pageIndex=i;A.renderCanvas();const copy=A.pageNode.cloneNode(true);copy.classList.remove('grid');copy.querySelectorAll('.selected,.slot-outline,.slot-empty').forEach(n=>n.remove());A.printHost.appendChild(copy)}A.state.pageIndex=old;A.renderAll();setTimeout(()=>window.print(),100)};
A.importPptxFile=async file=>{if(!file)return;A.setStatus('Analisando PPTX do Canva...');const response=await fetch('/api/encartes/import-pptx?name='+encodeURIComponent(file.name),{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:await file.arrayBuffer()});const data=await response.json();if(!response.ok||!data.ok)throw Error(data.error||'Falha ao analisar PPTX');A.snapshot();A.state.pages=(data.pages||[]).map((p,i)=>({...p,id:A.uid('pg'),name:p.name||('Página '+(i+1)),elements:[]}));if(!A.state.pages.length)A.state.pages=[A.newPage('Página 1')];A.state.pageIndex=0;A.state.selected=null;A.commit();A.setStatus('PPTX: '+(data.slotCount||0)+' bloco(s) reconhecido(s)');A.toast((data.pageCount||0)+' página(s) do Canva importada(s)')};
})();
