(() => {
'use strict';
const A=window.SR11;
const xml=(node,tag)=>[...node.getElementsByTagName(tag)];
const n=s=>A.norm(s);
const role=(text,name,size=0)=>{const t=n((name||'')+' '+(text||'')),raw=String(text||'').trim().toUpperCase();if(/PRECO[_ ]?CENTAV|CENTAVOS?/.test(t))return'PRECO_CENTAVOS';if(/PRECO[_ ]?REAIS|\bREAIS\b/.test(t))return'PRECO_REAIS';if(/PRECO.*(APP|CLUBE)|(APP|CLUBE).*PRECO/.test(t))return'PRECO_APP';if(raw==='R$'||/PRECO[_ ]?RS/.test(t))return'PRECO_RS';if(/IMAGEM|FOTO/.test(t))return'IMAGEM';if(/NOME.*PRODUTO|PRODUTO.*NOME|DESCRICAO/.test(t))return'NOME';if(/LIMITE/.test(t))return'LIMITE';if(/UNIDADE|UNID.*PRODUTO/.test(t))return'UNIDADE';if(/^[,.]\s*\d{2}$/.test(raw)&&size>=20)return'PRECO_CENTAVOS';if(/^\d{1,4}$/.test(raw)&&size>=32)return'PRECO_REAIS';if(/^(\/?)(UN|KG|CX|PCT|BDJ|DZ|LT)$/.test(raw))return'UNIDADE';return''};
const xfrm=node=>{const xf=xml(node,'a:xfrm')[0];if(!xf)return null;const off=xml(xf,'a:off')[0],ext=xml(xf,'a:ext')[0];if(!off||!ext)return null;return[+off.getAttribute('x'),+off.getAttribute('y'),+ext.getAttribute('cx'),+ext.getAttribute('cy')]};
const style=node=>{const r=xml(node,'a:rPr')[0]||xml(node,'a:defRPr')[0],out={font:'Segoe UI',fontSize:28,bold:false,italic:false,color:'#172033'};if(!r)return out;out.fontSize=Math.max(6,+(r.getAttribute('sz')||2800)/100);out.bold=['1','true'].includes(String(r.getAttribute('b')||'').toLowerCase());out.italic=['1','true'].includes(String(r.getAttribute('i')||'').toLowerCase());const latin=xml(r,'a:latin')[0],c=xml(r,'a:srgbClr')[0];if(latin?.getAttribute('typeface'))out.font=latin.getAttribute('typeface');if(c?.getAttribute('val'))out.color='#'+c.getAttribute('val').slice(0,6);return out};
const dist=(a,b)=>Math.hypot(a.x+a.w/2-b.x-b.w/2,a.y+a.h/2-b.y-b.h/2);
const path=(base,target)=>{const out=[];for(const x of (base+'/'+target).split('/')){if(!x||x==='.')continue;if(x==='..')out.pop();else out.push(x)}return out.join('/')};
const dataUrl=blob=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result||''));r.onerror=()=>reject(Error('Falha ao ler imagem do PPTX'));r.readAsDataURL(blob)});
const slots=(elements,w,h)=>{const texts=elements.filter(e=>e.type==='text'),imgs=elements.filter(e=>e.type==='image'),used=new Set();let anchors=texts.filter(e=>e.role==='PRECO_REAIS');if(!anchors.length){anchors=texts.filter(e=>/^\d{1,4}$/.test(String(e.text||'').trim())&&+(e.style?.fontSize||0)>=32);anchors.forEach(e=>e.role='PRECO_REAIS')}const out=[],maxd=Math.max(160,Math.min(w,h)*.30);anchors.sort((a,b)=>a.y-b.y||a.x-b.x).forEach((a,i)=>{const f={PRECO_REAIS:a};used.add(a.id);for(const r of ['PRECO_CENTAVOS','PRECO_RS','UNIDADE','NOME','LIMITE','PRECO_APP']){const c=texts.filter(e=>!used.has(e.id)&&e.role===r).sort((x,y)=>dist(a,x)-dist(a,y))[0];if(c&&dist(a,c)<=maxd*1.35){f[r]=c;used.add(c.id)}}if(!f.NOME){const c=texts.filter(e=>!used.has(e.id)&&!e.role&&/[A-ZÀ-Ý]{3}/i.test(e.text||'')&&e.y<a.y+a.h).sort((x,y)=>dist(a,x)-dist(a,y))[0];if(c&&dist(a,c)<=maxd*1.6){c.role='NOME';f.NOME=c;used.add(c.id)}}const im=imgs.filter(e=>!used.has(e.id)).sort((x,y)=>dist(a,x)-dist(a,y))[0];if(im&&dist(a,im)<=maxd*1.8){im.role='IMAGEM';f.IMAGEM=im;used.add(im.id)}if(!f.PRECO_CENTAVOS){const c=texts.filter(e=>!used.has(e.id)&&/^[,.]?\d{2}$/.test(String(e.text||'').trim())).sort((x,y)=>dist(a,x)-dist(a,y))[0];if(c&&dist(a,c)<=maxd){c.role='PRECO_CENTAVOS';f.PRECO_CENTAVOS=c;used.add(c.id)}}const vals=Object.values(f),x=Math.min(...vals.map(e=>e.x)),y=Math.min(...vals.map(e=>e.y)),rr=Math.max(...vals.map(e=>e.x+e.w)),bb=Math.max(...vals.map(e=>e.y+e.h));out.push({id:'slot_'+(i+1),index:i+1,x,y,w:rr-x,h:bb-y,fields:Object.fromEntries(Object.entries(f).map(([k,e])=>[k,{x:e.x,y:e.y,w:e.w,h:e.h,style:e.style||{},sourceId:e.id}]))})});elements.forEach(e=>e.placeholder=!!(e.role&&used.has(e.id)));return out};
A.PPTX={xml,n,role,xfrm,style,dist,path,dataUrl,slots};
})();
