(() => {
'use strict';
const A=window.SR11,E=A.E;if(!A||A.__BETA15_PROJECT__)return;A.__BETA15_PROJECT__=true;
A.VERSION_STORE='srstudio_encartes_named_versions_v1';
const readVersions=()=>{try{return JSON.parse(localStorage.getItem(A.VERSION_STORE)||'[]')||[]}catch{return[]}};
const writeVersions=v=>{try{localStorage.setItem(A.VERSION_STORE,JSON.stringify(v.slice(0,12)))}catch{}};
A.saveNamedVersion=name=>{const list=readVersions(),label=(name||'').trim()||('Versão '+new Date().toLocaleString('pt-BR'));list.unshift({id:A.uid('ver'),name:label,at:new Date().toISOString(),state:A.copy(A.state)});writeVersions(list);A.toast('Versão salva: '+label);return label};
A.restoreNamedVersion=id=>{const item=readVersions().find(x=>x.id===id);if(!item)return false;A.snapshot();A.state=A.copy(item.state);A.commit();A.toast('Versão restaurada: '+item.name);return true};
A.exportProject=()=>{const payload={format:'SR_STUDIO_ENCARTES_PROJECT_1',savedAt:new Date().toISOString(),version:A.VERSION,state:A.state,templateMemory:A.loadTemplateMemory()};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(A.state.projectName||'encarte').replace(/[^a-z0-9_-]+/gi,'_')+'.srstudio.json';document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},500);A.toast('Backup do projeto exportado.')};
A.importProject=async file=>{const data=JSON.parse(await file.text());if(data?.format!=='SR_STUDIO_ENCARTES_PROJECT_1'||!data.state?.pages||!data.state?.products)throw Error('Arquivo de projeto inválido.');A.snapshot();A.state=data.state;if(data.templateMemory)A.saveTemplateMemory(data.templateMemory);A.commit();A.toast('Projeto restaurado com sucesso.')};
function modal(){const bg=E('div','modal-bg'),box=E('div','modal');box.appendChild(E('h2','','Versões do projeto'));const name=E('input','input');name.placeholder='Nome da versão (ex.: Quinta Filé aprovado)';const save=E('button','btn','Salvar versão atual');save.addEventListener('click',()=>{A.saveNamedVersion(name.value);bg.remove()});box.append(name,save,E('div','title','Versões salvas'));const list=readVersions();if(!list.length)box.appendChild(E('div','help','Nenhuma versão manual salva ainda.'));for(const v of list){const row=E('div','layer-row'),info=E('div');info.append(E('b','',v.name),E('div','help',new Date(v.at).toLocaleString('pt-BR')));const restore=E('button','btn','Restaurar');restore.addEventListener('click',()=>{if(confirm('Restaurar esta versão?')){A.restoreNamedVersion(v.id);bg.remove()}});const del=E('button','btn danger','Excluir');del.addEventListener('click',()=>{writeVersions(readVersions().filter(x=>x.id!==v.id));bg.remove();modal()});row.style.gridTemplateColumns='1fr auto auto';row.append(info,restore,del);box.appendChild(row)}const close=E('button','btn','Fechar');close.addEventListener('click',()=>bg.remove());box.appendChild(close);bg.appendChild(box);document.body.appendChild(bg)}
function install(){const top=document.querySelector('.top'),spacer=top?.querySelector('.spacer');if(!top||!spacer||document.getElementById('sr15-backup'))return;const backup=E('button');backup.id='sr15-backup';backup.textContent='Backup';backup.addEventListener('click',A.exportProject);const versions=E('button');versions.textContent='Versões';versions.addEventListener('click',modal);const inp=E('input','file');inp.type='file';inp.accept='.json,.srstudio.json';inp.style.display='none';inp.addEventListener('change',async()=>{try{if(inp.files[0])await A.importProject(inp.files[0])}catch(e){A.toast(e.message||'Falha ao abrir projeto')}finally{inp.value=''}});const open=E('button');open.textContent='Abrir projeto';open.addEventListener('click',()=>inp.click());top.insertBefore(backup,spacer);top.insertBefore(versions,spacer);top.insertBefore(open,spacer);top.appendChild(inp)}install();
console.info('[SR Studio] Beta 15 backup e versões ativos');
})();
