(() => {
'use strict';
const A=window.SR11,E=A.E;if(!A||A.__BETA15_RENDER__)return;A.__BETA15_RENDER__=true;
const previous=A.renderCanvas;
const pos=(n,b)=>{n.style.left=b.x+'px';n.style.top=b.y+'px';n.style.width=b.w+'px';n.style.height=b.h+'px'};
const value=(role,p)=>{const q=A.priceParts(p.price);if(role==='NOME')return p.name||'';if(role==='PRECO_RS')return'R$';if(role==='PRECO_REAIS')return q.reais;if(role==='PRECO_CENTAVOS')return q.centavos;if(role==='UNIDADE')return p.unit||'UN';if(role==='LIMITE')return p.limit?('LIMITE DE '+p.limit+' POR CPF'):'';if(role==='PRECO_APP')return p.app?('R$ '+p.app):'';return''};
function css(){if(document.getElementById('sr15-css'))return;const s=document.createElement('style');s.id='sr15-css';s.textContent=`.pro-part{position:absolute;box-sizing:border-box}.part-edit-mode .pro-part{cursor:move}.pro-part.part-selected{outline:2px dashed #00a2ff;outline-offset:2px}.pro-part.part-locked{cursor:not-allowed!important}.part-handle{position:absolute;width:10px;height:10px;right:-5px;bottom:-5px;border:2px solid #fff;background:#00a2ff;border-radius:2px;cursor:nwse-resize;z-index:120}.pro-guide{position:absolute;pointer-events:none;background:#00a2ff;z-index:150}.pro-guide.v{top:0;bottom:0;width:1px}.pro-guide.h{left:0;right:0;height:1px}.pro-toolbar{display:flex;gap:6px;flex-wrap:wrap;margin:8px 0}.pro-toolbar button.active{background:#9b5cff;color:#fff;border-color:#9b5cff}.layer-row{display:grid;grid-template-columns:1fr auto auto auto;gap:4px;align-items:center;padding:5px 0;border-bottom:1px solid #e9edf4}.layer-row button{padding:4px 6px}.part-metrics{display:grid;grid-template-columns:1fr 1fr;gap:6px}.part-metrics label{font-size:10px;font-weight:800;color:#6b7280}.part-metrics input,.part-metrics select{width:100%;box-sizing:border-box;padding:6px;border:1px solid #d9dfeb;border-radius:6px}.model-badge{display:inline-block;padding:4px 7px;background:#efe9ff;color:#5a2aa8;border-radius:999px;font-size:10px;font-weight:900}.compare-original .slot-outline,.compare-original .slot-empty{display:none!important}@media print{.part-handle,.pro-guide{display:none!important}.pro-part.part-selected{outline:none!important}}`;document.head.appendChild(s)}css();
function styleText(n,s={},role){n.style.fontFamily=s.font||'Segoe UI';n.style.fontWeight=s.bold?'900':'700';n.style.fontStyle=s.italic?'italic':'normal';n.style.color=s.color||'#172033';const a=s.align||'center';n.style.textAlign=a;n.style.justifyContent=a==='right'?'flex-end':a==='left'?'flex-start':'center';const v=s.vAlign||'center';n.style.alignItems=v==='top'?'flex-start':v==='bottom'?'flex-end':'center';n.style.lineHeight=role==='NOME'?'1.02':'1';n.style.padding=role==='NOME'?'1px 3px':'1px';n.style.overflow='hidden';n.style.boxSizing='border-box'}
function fitText(n,role,f){const s=f.style||{},manual=Number(s.fontSize||0),base=manual||20;let min,max;if(role==='NOME'){min=Math.max(6,base*.38);max=Math.max(base,Math.min(base*1.25,f.h*.95));n.style.whiteSpace='normal';n.style.overflowWrap='break-word'}else{min=Math.max(6,base*.45);max=Math.max(base,Math.min(base*1.35,f.h*1.12));n.style.whiteSpace='nowrap'}let lo=min,hi=max,best=min;for(let i=0;i<14;i++){const m=(lo+hi)/2;n.style.fontSize=m+'px';if(n.scrollWidth<=n.clientWidth+1&&n.scrollHeight<=n.clientHeight+1){best=m;lo=m}else hi=m}n.style.fontSize=best+'px'}
function guide(kind,v){const g=E('div','pro-guide '+kind);if(kind==='v')g.style.left=v+'px';else g.style.top=v+'px';A.pageNode.appendChild(g);return g}
function snapAxis(start,size,cands,th=6){let best={delta:0,line:null,d:th+1};for(const c of cands){for(const p of [start,start+size/2,start+size]){const d=Math.abs(c-p);if(d<best.d){best={delta:c-p,line:c,d}}}}return best.d<=th?best:{delta:0,line:null}}
function candidates(pg,e,role){const xs=[0,pg.width/2,pg.width],ys=[0,pg.height/2,pg.height];for(const other of pg.elements||[]){if(!other.slotId)continue;const slot=(pg.templateSlots||[]).find(s=>s.id===other.slotId);if(!slot)continue;for(const [r,b] of Object.entries(slot.fields||{})){if(other.id===e.id&&r===role)continue;const f=A.effectiveField(other,r,b);xs.push(f.x,f.x+f.w/2,f.x+f.w);ys.push(f.y,f.y+f.h/2,f.y+f.h)}}return{xs,ys}}
function bindPart(node,e,role,base,pg){if(!A.state.partEditMode)return;const edit=A.ensurePart(e,role);node.style.pointerEvents='auto';node.classList.toggle('part-locked',Boolean(edit.locked));node.addEventListener('pointerdown',ev=>{if(ev.button!==0||ev.target.classList.contains('part-handle'))return;ev.stopPropagation();A.state.selected=e.id;A.state.selectedPart=role;if(edit.locked){A.emit();return}A.snapshot();let sx=ev.clientX,sy=ev.clientY,ox=Number(edit.dx)||0,oy=Number(edit.dy)||0;const scale=Number(A.state.zoom)||1,c=candidates(pg,e,role);node.setPointerCapture(ev.pointerId);let guides=[];const move=mv=>{let dx=ox+(mv.clientX-sx)/scale,dy=oy+(mv.clientY-sy)/scale;let f=A.effectiveField({...e,partEdits:{...e.partEdits,[role]:{...edit,dx,dy}}},role,base);guides.forEach(g=>g.remove());guides=[];const xs=snapAxis(f.x,f.w,c.xs),ys=snapAxis(f.y,f.h,c.ys);dx+=xs.delta;dy+=ys.delta;if(A.state.snap){dx=Math.round(dx);dy=Math.round(dy)}edit.dx=dx;edit.dy=dy;f=A.effectiveField(e,role,base);node.style.left=f.x+'px';node.style.top=f.y+'px';if(xs.line!==null)guides.push(guide('v',xs.line));if(ys.line!==null)guides.push(guide('h',ys.line))};const up=()=>{node.removeEventListener('pointermove',move);node.removeEventListener('pointerup',up);guides.forEach(g=>g.remove());A.save();A.emit()};node.addEventListener('pointermove',move);node.addEventListener('pointerup',up);A.renderInspector?.()});if(A.state.selected===e.id&&A.state.selectedPart===role&&!edit.locked){const h=E('span','part-handle');node.appendChild(h);h.addEventListener('pointerdown',ev=>{ev.stopPropagation();A.snapshot();let sx=ev.clientX,sy=ev.clientY,ow=Number(edit.dw)||0,oh=Number(edit.dh)||0;const scale=Number(A.state.zoom)||1;h.setPointerCapture(ev.pointerId);const mv=m=>{edit.dw=Math.max(-(base.w-12),ow+(m.clientX-sx)/scale);edit.dh=Math.max(-(base.h-12),oh+(m.clientY-sy)/scale);const f=A.effectiveField(e,role,base);node.style.width=f.w+'px';node.style.height=f.h+'px';if(role!=='IMAGEM')fitText(node,role,f)};const up=()=>{h.removeEventListener('pointermove',mv);h.removeEventListener('pointerup',up);A.save();A.emit()};h.addEventListener('pointermove',mv);h.addEventListener('pointerup',up)})}}
function imageSafe(slot,e,f){const eff=A.effectiveField(e,'IMAGEM',f),px=Math.max(2,eff.w*.035),py=Math.max(2,eff.h*.035);let b={...eff,x:eff.x+px,y:eff.y+py,w:Math.max(16,eff.w-px*2),h:Math.max(16,eff.h-py*2)};for(const r of ['PRECO_REAIS','PRECO_CENTAVOS','PRECO_RS','UNIDADE']){const q0=slot.fields?.[r];if(!q0)continue;const q=A.effectiveField(e,r,q0);const ix=Math.max(0,Math.min(b.x+b.w,q.x+q.w)-Math.max(b.x,q.x)),iy=Math.max(0,Math.min(b.y+b.h,q.y+q.h)-Math.max(b.y,q.y));if(ix*iy<=0)continue;if(q.x>b.x+b.w/2)b.w=Math.max(16,q.x-b.x-3);else if(q.y>b.y+b.h/2)b.h=Math.max(16,q.y-b.y-3)}return b}
function addImage(pg,slot,e,p,base){if(!p.image)return;const b=imageSafe(slot,e,base),edit=A.ensurePart(e,'IMAGEM'),wrap=E('div','pro-part image-part'+(A.state.selected===e.id&&A.state.selectedPart==='IMAGEM'?' part-selected':''));wrap.dataset.role='IMAGEM';wrap.style.overflow='hidden';wrap.style.zIndex=String(edit.z??8);wrap.style.borderRadius=base.autoDetected?Math.min(24,Math.max(7,Math.min(b.w,b.h)*.10))+'px':'0';pos(wrap,b);const img=E('img');img.src=p.image;img.alt=p.name||'Produto';img.style.width='100%';img.style.height='100%';img.style.objectFit=edit.fit||base.fit||base.style?.fit||'contain';img.style.objectPosition=(edit.focusX??50)+'% '+(edit.focusY??50)+'%';img.style.transform='scale('+(Number(edit.imageScale)||1)+')';img.style.transformOrigin=img.style.objectPosition;img.style.display='block';wrap.appendChild(img);A.pageNode.appendChild(wrap);bindPart(wrap,e,'IMAGEM',base,pg)}
function addText(pg,e,p,role,base){const f=A.effectiveField(e,role,base),edit=A.ensurePart(e,role),n=E('div','pro-part text slot-field'+(A.state.selected===e.id&&A.state.selectedPart===role?' part-selected':''),value(role,p));n.dataset.role=role;n.style.zIndex=String(edit.z??45);styleText(n,f.style,role);pos(n,f);A.pageNode.appendChild(n);fitText(n,role,f);bindPart(n,e,role,base,pg);if(document.fonts?.ready)document.fonts.ready.then(()=>fitText(n,role,A.effectiveField(e,role,base)))}
function renderTemplate(pg){const bg=E('img','tpl-img');bg.src=pg.backgroundUrl;bg.alt='Design original do Canva';bg.style.objectFit='fill';bg.style.pointerEvents='none';bg.style.zIndex='1';pos(bg,{x:0,y:0,w:pg.width,h:pg.height});A.pageNode.appendChild(bg)}
function renderSlot(pg,e,p,slot){if(slot.fields?.IMAGEM)addImage(pg,slot,e,p,slot.fields.IMAGEM);for(const r of ['NOME','PRECO_RS','PRECO_REAIS','PRECO_CENTAVOS','UNIDADE','LIMITE','PRECO_APP'])if(slot.fields?.[r])addText(pg,e,p,r,slot.fields[r]);const out=E('div','slot-outline'+(A.state.selected===e.id?' selected':''));out.style.zIndex='80';out.style.pointerEvents=A.state.partEditMode?'none':'auto';pos(out,slot);out.addEventListener('click',ev=>{ev.stopPropagation();A.state.selected=e.id;A.state.selectedPart=null;A.emit()});A.pageNode.appendChild(out)}
A.renderCanvas=()=>{const pg=A.page();if(!pg?.backgroundUrl)return previous();A.pageNode.replaceChildren();A.pageNode.classList.toggle('part-edit-mode',A.state.partEditMode);A.pageNode.classList.toggle('compare-original',A.state.compareOriginal);A.pageNode.style.width=pg.width+'px';A.pageNode.style.height=pg.height+'px';A.zoomNode.style.transform='scale('+A.state.zoom+')';A.zoomNode.style.marginBottom='-'+(pg.height*(1-A.state.zoom))+'px';renderTemplate(pg);if(A.state.compareOriginal)return;const filled=new Map((pg.elements||[]).filter(e=>e.slotId).map(e=>[e.slotId,e]));for(const s of pg.templateSlots||[])if(!filled.has(s.id)){const x=E('div','slot-empty','PRODUTO '+s.index);x.style.zIndex='70';pos(x,s);A.pageNode.appendChild(x)}for(const e of pg.elements||[]){const p=A.state.products.find(x=>x.id===e.productId);if(!p)continue;const s=(pg.templateSlots||[]).find(x=>x.id===e.slotId);if(s)renderSlot(pg,e,p,s);else{return previous()}}};
console.info('[SR Studio] Beta 15 editor manual por partes ativo');
})();
