(() => {
'use strict';
const A=window.SR11,E=A.E;if(!A||A.__BETA15_TOOLS__)return;A.__BETA15_TOOLS__=true;
function button(label,fn,cls='btn'){const b=E('button',cls,label);b.type='button';b.addEventListener('click',fn);return b}
function field(label,value,onchange,type='number'){const wrap=E('label');wrap.style.fontSize='10px';wrap.style.fontWeight='800';wrap.textContent=label;const i=E('input','input');i.type=type;i.value=value??'';i.addEventListener('change',()=>onchange(i.value));wrap.appendChild(i);return wrap}
function select(label,value,items,onchange){const wrap=E('label');wrap.style.fontSize='10px';wrap.style.fontWeight='800';wrap.textContent=label;const s=E('select','input');for(const [v,t] of items){const o=E('option','',t);o.value=v;if(String(v)===String(value))o.selected=true;s.appendChild(o)}s.addEventListener('change',()=>onchange(s.value));wrap.appendChild(s);return wrap}
function selectedContext(){const pg=A.page(),e=A.selectedElement(),slot=A.selectedSlot(),p=e&&A.state.products.find(x=>x.id===e.productId);return{pg,e,slot,p}}
function setPart(role,patch){const {e}=selectedContext();if(!e||!role)return;A.snapshot();Object.assign(A.ensurePart(e,role),patch);A.state.selectedPart=role;A.commit()}
function addTopControls(){const top=document.querySelector('.top');if(!top||document.getElementById('sr15-edit'))return;const spacer=top.querySelector('.spacer');const edit=button('✥ Editar partes',()=>{A.state.partEditMode=!A.state.partEditMode;if(!A.state.partEditMode)A.state.selectedPart=null;A.save();A.emit();sync()},'');edit.id='sr15-edit';const original=button('◐ Original',()=>{A.state.compareOriginal=!A.state.compareOriginal;A.save();A.renderCanvas();sync()},'');original.id='sr15-original';const learn=button('◆ Aprender modelo',()=>A.learnTemplate(),'');learn.id='sr15-learn';const fill=button('Preencher página',()=>A.fillCurrentPage(),'');fill.id='sr15-fill';for(const b of [edit,original,learn,fill])top.insertBefore(b,spacer);function sync(){edit.classList.toggle('active',A.state.partEditMode);original.classList.toggle('active',A.state.compareOriginal)}sync()}
function appendGeneralTools(host){const {pg,e,slot}=selectedContext(),bar=E('div','pro-toolbar');bar.append(button(A.state.partEditMode?'✓ Editando partes':'Editar partes',()=>{A.state.partEditMode=!A.state.partEditMode;A.save();A.emit()}),button('Original / preenchido',()=>{A.state.compareOriginal=!A.state.compareOriginal;A.save();A.renderCanvas()}),button('Aprender este modelo',()=>A.learnTemplate()),button('Aplicar modelo salvo',()=>A.applyTemplateMemory()),button('Preencher página',()=>A.fillCurrentPage()));host.appendChild(E('div','title','Modo profissional'));host.appendChild(bar);if(pg?.templateSlots?.length)host.appendChild(E('span','model-badge','Template '+A.templateKey(pg).slice(-6).toUpperCase()+(slot?' · bloco '+A.slotType(pg,slot):'')));if(e){const reset=E('div','pro-toolbar');reset.append(button('Resetar produto',()=>A.resetSelectedProduct()),button('Resetar página',()=>A.resetCurrentPage()));host.appendChild(reset)}}
function appendReplace(host){const {e,p}=selectedContext();if(!e||!p)return;host.appendChild(E('div','title','Trocar produto mantendo o bloco'));const s=E('select','input');for(const x of A.state.products){const o=E('option','',x.name||'SEM NOME');o.value=x.id;if(x.id===p.id)o.selected=true;s.appendChild(o)}const b=button('Trocar produto',()=>{if(A.replaceSelectedProduct(s.value))A.toast('Produto substituído mantendo os ajustes.');});host.append(s,b)}
function appendPartEditor(host){const {pg,e,slot}=selectedContext();if(!e||!slot)return;const roles=A.availableParts();if(!roles.length)return;if(!roles.includes(A.state.selectedPart))A.state.selectedPart=roles[0];const role=A.state.selectedPart,base=slot.fields[role],m=A.ensurePart(e,role),eff=A.effectiveField(e,role,base);host.appendChild(E('div','title','Editar parte'));const choose=E('select','input');for(const r of roles){const o=E('option','',A.partLabel(r));o.value=r;if(r===role)o.selected=true;choose.appendChild(o)}choose.addEventListener('change',()=>{A.state.selectedPart=choose.value;A.save();A.emit()});host.appendChild(choose);
const metrics=E('div','part-metrics');metrics.append(field('Mover X',Math.round(m.dx||0),v=>setPart(role,{dx:Number(v)||0})),field('Mover Y',Math.round(m.dy||0),v=>setPart(role,{dy:Number(v)||0})),field('Largura Δ',Math.round(m.dw||0),v=>setPart(role,{dw:Number(v)||0})),field('Altura Δ',Math.round(m.dh||0),v=>setPart(role,{dh:Number(v)||0})));host.appendChild(metrics);
if(role==='IMAGEM'){const row=E('div','part-metrics');row.append(select('Encaixe',m.fit||base.fit||base.style?.fit||'contain',[['contain','Mostrar inteira'],['cover','Preencher caixa'],['fill','Esticar']],v=>setPart(role,{fit:v})),field('Zoom imagem',m.imageScale??1,v=>setPart(role,{imageScale:Math.max(.2,Math.min(4,Number(v)||1))})));host.appendChild(row);const focus=E('div','part-metrics');focus.append(field('Foco X %',m.focusX??50,v=>setPart(role,{focusX:Math.max(0,Math.min(100,Number(v)||50))})),field('Foco Y %',m.focusY??50,v=>setPart(role,{focusY:Math.max(0,Math.min(100,Number(v)||50))})));host.appendChild(focus)}else{const row=E('div','part-metrics');row.append(field('Fonte',m.fontSize??base.style?.fontSize??'',v=>setPart(role,{fontSize:Number(v)||undefined})),select('Alinhamento',m.align||base.style?.align||'center',[['left','Esquerda'],['center','Centro'],['right','Direita']],v=>setPart(role,{align:v})));host.appendChild(row)}
const lock=E('label');lock.style.display='flex';lock.style.gap='6px';lock.style.alignItems='center';const chk=E('input');chk.type='checkbox';chk.checked=Boolean(m.locked);chk.addEventListener('change',()=>setPart(role,{locked:chk.checked}));lock.append(chk,E('span','',chk.checked?'Parte bloqueada':'Bloquear esta parte'));host.appendChild(lock);
const actions=E('div','pro-toolbar');actions.append(button('Resetar parte',()=>A.resetSelectedPart()),button('Copiar parte → semelhantes',()=>A.copyPartToSimilar()),button('Copiar produto → semelhantes',()=>A.copyProductAdjustmentsToSimilar()));host.appendChild(actions);host.appendChild(E('div','help','Arraste diretamente no encarte para mover. Use o quadradinho azul para redimensionar. Setas movem 1 px; Shift + seta move 10 px.'));
host.appendChild(E('div','title','Camadas do produto'));for(const r of roles){const mm=A.ensurePart(e,r),row=E('div','layer-row');const name=button((A.state.selectedPart===r?'● ':'')+A.partLabel(r),()=>{A.state.selectedPart=r;A.emit()},'btn');const back=button('↓',()=>setPart(r,{z:(Number(mm.z)||(r==='IMAGEM'?8:45))-5}),'btn');const front=button('↑',()=>setPart(r,{z:(Number(mm.z)||(r==='IMAGEM'?8:45))+5}),'btn');const lockb=button(mm.locked?'🔒':'🔓',()=>setPart(r,{locked:!mm.locked}),'btn');row.append(name,back,front,lockb);host.appendChild(row)}host.appendChild(E('div','help','Posição atual: X '+Math.round(eff.x)+' · Y '+Math.round(eff.y)+' · '+Math.round(eff.w)+'×'+Math.round(eff.h)+' px'))}
const oldInspector=A.renderInspector;A.renderInspector=()=>{oldInspector();appendGeneralTools(A.inspectorNode);appendPartEditor(A.inspectorNode);appendReplace(A.inspectorNode)};
addTopControls();
document.addEventListener('keydown',ev=>{if(!A.state.partEditMode||!A.state.selectedPart||['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName))return;const map={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]};if(!map[ev.key])return;const e=A.selectedElement(),role=A.state.selectedPart;if(!e||A.ensurePart(e,role).locked)return;ev.preventDefault();const k=ev.shiftKey?10:1,[dx,dy]=map[ev.key];A.snapshot();const m=A.ensurePart(e,role);m.dx=(Number(m.dx)||0)+dx*k;m.dy=(Number(m.dy)||0)+dy*k;A.commit()});
A.emit();
console.info('[SR Studio] Beta 15 ferramentas PRO ativas');
})();
