(() => {
'use strict';
const A=window.SR11;if(!A||A.__BETA16_CORE__)return;A.__BETA16_CORE__=true;
A.VERSION='4.0.16 • Stable 4';
const ver=document.querySelector('.ver');if(ver)ver.textContent=A.VERSION;
A.state.partEditMode=true;
A.state.proSelection=Array.isArray(A.state.proSelection)?A.state.proSelection:[];
A.state.cropKey=A.state.cropKey||null;
A.state.proGroups=A.state.proGroups||{};
const key=(eid,role)=>eid+'::'+role;
const parse=k=>{const i=String(k).indexOf('::');return i<0?['','']:[k.slice(0,i),k.slice(i+2)]};
A.partKey=key;A.parsePartKey=parse;
A.partContext=k=>{const [eid,role]=parse(k),pg=A.page(),e=(pg.elements||[]).find(x=>x.id===eid);if(!e||!e.slotId)return null;const slot=(pg.templateSlots||[]).find(s=>s.id===e.slotId),base=slot?.fields?.[role];if(!slot||!base)return null;return{k,eid,role,pg,e,slot,base,edit:A.ensurePart(e,role),field:A.effectiveField(e,role,base),product:A.state.products.find(p=>p.id===e.productId)||null}};
A.selectionContexts=()=>{const out=[];for(const k of A.state.proSelection||[]){const c=A.partContext(k);if(c)out.push(c)}return out};
A.groupKeysFor=k=>{const c=A.partContext(k),gid=c?.edit?.groupId;if(!gid)return[k];return Object.keys(A.state.proGroups||{}).includes(gid)?(A.state.proGroups[gid]||[]):[k]};
A.selectPart=(eid,role,mode='replace')=>{let k=key(eid,role),keys=A.groupKeysFor(k);let sel=[...(A.state.proSelection||[])];if(mode==='toggle'){for(const x of keys){sel=sel.includes(x)?sel.filter(v=>v!==x):[...sel,x]}}else if(mode==='add'){for(const x of keys)if(!sel.includes(x))sel.push(x)}else sel=[...keys];A.state.proSelection=[...new Set(sel)];A.state.selected=eid;A.state.selectedPart=role;A.save();A.emit();return A.state.proSelection};
A.clearProSelection=()=>{A.state.proSelection=[];A.state.cropKey=null;A.state.selectedPart=null;A.save();A.emit()};
A.selectionBounds=()=>{const cs=A.selectionContexts();if(!cs.length)return null;const xs=cs.map(c=>c.field.x),ys=cs.map(c=>c.field.y),rs=cs.map(c=>c.field.x+c.field.w),bs=cs.map(c=>c.field.y+c.field.h);return{x:Math.min(...xs),y:Math.min(...ys),w:Math.max(...rs)-Math.min(...xs),h:Math.max(...bs)-Math.min(...ys)}};
A.moveSelection=(dx,dy,commit=true)=>{const cs=A.selectionContexts().filter(c=>!c.edit.locked);if(!cs.length)return;for(const c of cs){c.edit.dx=(Number(c.edit.dx)||0)+dx;c.edit.dy=(Number(c.edit.dy)||0)+dy}if(commit)A.commit();else{A.save();A.renderCanvas();A.renderInspector?.()}};
A.setSelectionOpacity=v=>{const n=Math.max(0,Math.min(1,Number(v)));for(const c of A.selectionContexts())c.edit.opacity=n;A.commit()};
A.setSelectionRotation=v=>{const n=Number(v)||0;for(const c of A.selectionContexts().filter(c=>!c.edit.locked))c.edit.rotation=n;A.commit()};
A.lockSelection=locked=>{for(const c of A.selectionContexts())c.edit.locked=locked===undefined?!c.edit.locked:Boolean(locked);A.commit()};
A.layerSelection=(mode)=>{const cs=A.selectionContexts();if(!cs.length)return;const zs=[];for(const e of A.page().elements||[])if(e.slotId){const s=(A.page().templateSlots||[]).find(x=>x.id===e.slotId);for(const [r,b] of Object.entries(s?.fields||{})){const m=A.ensurePart(e,r);zs.push(Number.isFinite(Number(m.z))?Number(m.z):(r==='IMAGEM'?8:45))}}const min=Math.min(1,...zs),max=Math.max(45,...zs);for(const c of cs){const cur=Number.isFinite(Number(c.edit.z))?Number(c.edit.z):(c.role==='IMAGEM'?8:45);c.edit.z=mode==='front'?max+1:mode==='back'?Math.max(2,min-1):mode==='forward'?cur+1:Math.max(2,cur-1)}A.commit()};
A.groupSelection=()=>{const keys=[...(A.state.proSelection||[])];if(keys.length<2){A.toast('Selecione duas ou mais partes.');return null}const gid='grp_'+A.uid('g');A.state.proGroups[gid]=keys;for(const k of keys){const c=A.partContext(k);if(c)c.edit.groupId=gid}A.commit();A.toast('Elementos agrupados.');return gid};
A.ungroupSelection=()=>{const gids=new Set(A.selectionContexts().map(c=>c.edit.groupId).filter(Boolean));if(!gids.size){A.toast('A seleção não está agrupada.');return}for(const gid of gids){for(const k of A.state.proGroups[gid]||[]){const c=A.partContext(k);if(c)delete c.edit.groupId}delete A.state.proGroups[gid]}A.commit();A.toast('Grupo desfeito.')};
A.alignSelection=mode=>{const cs=A.selectionContexts().filter(c=>!c.edit.locked);if(cs.length<2)return;A.snapshot();const b=A.selectionBounds();for(const c of cs){let nx=c.field.x,ny=c.field.y;if(mode==='left')nx=b.x;if(mode==='center')nx=b.x+(b.w-c.field.w)/2;if(mode==='right')nx=b.x+b.w-c.field.w;if(mode==='top')ny=b.y;if(mode==='middle')ny=b.y+(b.h-c.field.h)/2;if(mode==='bottom')ny=b.y+b.h-c.field.h;c.edit.dx=(Number(c.edit.dx)||0)+(nx-c.field.x);c.edit.dy=(Number(c.edit.dy)||0)+(ny-c.field.y)}A.commit()};
A.distributeSelection=axis=>{const cs=A.selectionContexts().filter(c=>!c.edit.locked);if(cs.length<3)return;A.snapshot();const sorted=[...cs].sort((a,b)=>axis==='x'?a.field.x-b.field.x:a.field.y-b.field.y);const first=sorted[0].field,last=sorted.at(-1).field;if(axis==='x'){const total=sorted.reduce((s,c)=>s+c.field.w,0),gap=((last.x+last.w)-first.x-total)/(sorted.length-1);let x=first.x;for(const c of sorted){c.edit.dx=(Number(c.edit.dx)||0)+(x-c.field.x);x+=c.field.w+gap}}else{const total=sorted.reduce((s,c)=>s+c.field.h,0),gap=((last.y+last.h)-first.y-total)/(sorted.length-1);let y=first.y;for(const c of sorted){c.edit.dy=(Number(c.edit.dy)||0)+(y-c.field.y);y+=c.field.h+gap}}A.commit()};
A.resizeSelectionTo=(box,startBox,startFields)=>{const cs=A.selectionContexts().filter(c=>!c.edit.locked);if(!cs.length)return;const sx=startBox.w?box.w/startBox.w:1,sy=startBox.h?box.h/startBox.h:1;for(const c of cs){const st=startFields[c.k];if(!st)continue;const nx=box.x+(st.x-startBox.x)*sx,ny=box.y+(st.y-startBox.y)*sy,nw=Math.max(8,st.w*sx),nh=Math.max(8,st.h*sy);c.edit.dx=nx-c.base.x;c.edit.dy=ny-c.base.y;c.edit.dw=nw-c.base.w;c.edit.dh=nh-c.base.h}};
A.commitRoleText=(ctx,text)=>{const p=ctx?.product;if(!p)return;const t=String(text??'').trim();if(ctx.role==='NOME')p.name=t;else if(ctx.role==='UNIDADE')p.unit=t.toUpperCase();else if(ctx.role==='LIMITE')p.limit=t.replace(/^LIMITE\s+DE\s+/i,'').replace(/\s+POR\s+CPF$/i,'');else if(ctx.role==='PRECO_APP')p.app=A.money(t.replace(/^R\$\s*/i,''));else if(ctx.role==='PRECO_REAIS'||ctx.role==='PRECO_CENTAVOS'){const q=A.priceParts(p.price);let reais=q.reais,cents=q.centavos.replace(',','');if(ctx.role==='PRECO_REAIS')reais=t.replace(/\D/g,'')||'0';else cents=(t.replace(/\D/g,'')||'00').padStart(2,'0').slice(-2);p.price=A.money(reais+','+cents)}A.commit()};
A.hideSelection=hidden=>{for(const c of A.selectionContexts())c.edit.hidden=hidden===undefined?true:Boolean(hidden);A.commit()};
A.flipSelection=axis=>{for(const c of A.selectionContexts().filter(c=>c.role==='IMAGEM')){if(axis==='x')c.edit.flipX=!c.edit.flipX;else c.edit.flipY=!c.edit.flipY}A.commit()};
A.duplicateSelectionProduct=()=>{const ids=[...new Set(A.selectionContexts().map(c=>c.eid))];if(ids.length!==1){A.toast('Duplique um produto por vez.');return false}A.state.selected=ids[0];return A.duplicateSelected()};
console.info('[SR Studio] Beta 16 interaction core ativo');
})();

(() => {
'use strict';
const A=window.SR11,E=A.E;if(!A||A.__BETA16_CANVAS__)return;A.__BETA16_CANVAS__=true;
const fallback=A.renderCanvas;
const pos=(n,b)=>{n.style.left=b.x+'px';n.style.top=b.y+'px';n.style.width=b.w+'px';n.style.height=b.h+'px'};
const val=(role,p)=>{const q=A.priceParts(p.price);if(role==='NOME')return p.name||'';if(role==='PRECO_RS')return'R$';if(role==='PRECO_REAIS')return q.reais;if(role==='PRECO_CENTAVOS')return q.centavos;if(role==='UNIDADE')return p.unit||'UN';if(role==='LIMITE')return p.limit?('LIMITE DE '+p.limit+' POR CPF'):'';if(role==='PRECO_APP')return p.app?('R$ '+p.app):'';return''};
function injectCSS(){if(document.getElementById('sr16-css'))return;const s=document.createElement('style');s.id='sr16-css';s.textContent=`.sr16-part{position:absolute;box-sizing:border-box;transform-origin:center center}.sr16-part:not(.locked){cursor:move}.sr16-part.locked{cursor:not-allowed}.sr16-part.image{overflow:hidden}.sr16-part img{width:100%;height:100%;display:block;pointer-events:none}.sr16-part.editing-text{outline:2px solid #7c3aed!important;background:#ffffff12;cursor:text}.sr16-selection{position:absolute;border:1.5px solid #7c3aed;box-sizing:border-box;z-index:300;pointer-events:none}.sr16-selection.multi{border-style:dashed}.sr16-handle{position:absolute;width:10px;height:10px;background:#fff;border:1.5px solid #7c3aed;border-radius:50%;box-sizing:border-box;pointer-events:auto;z-index:305}.sr16-handle.nw{left:-5px;top:-5px;cursor:nwse-resize}.sr16-handle.n{left:50%;top:-5px;transform:translateX(-50%);cursor:ns-resize}.sr16-handle.ne{right:-5px;top:-5px;cursor:nesw-resize}.sr16-handle.e{right:-5px;top:50%;transform:translateY(-50%);cursor:ew-resize}.sr16-handle.se{right:-5px;bottom:-5px;cursor:nwse-resize}.sr16-handle.s{left:50%;bottom:-5px;transform:translateX(-50%);cursor:ns-resize}.sr16-handle.sw{left:-5px;bottom:-5px;cursor:nesw-resize}.sr16-handle.w{left:-5px;top:50%;transform:translateY(-50%);cursor:ew-resize}.sr16-rotate-line{position:absolute;width:1px;height:24px;background:#7c3aed;left:50%;top:-29px;transform:translateX(-50%)}.sr16-rotate{position:absolute;width:14px;height:14px;background:#fff;border:1.5px solid #7c3aed;border-radius:50%;left:50%;top:-42px;transform:translateX(-50%);pointer-events:auto;cursor:grab;z-index:306}.sr16-guide{position:absolute;background:#d946ef;pointer-events:none;z-index:290}.sr16-guide.v{width:1px;top:0;bottom:0}.sr16-guide.h{height:1px;left:0;right:0}.sr16-marquee{position:absolute;border:1px solid #7c3aed;background:#7c3aed18;z-index:320;pointer-events:none}.sr16-crop .sr16-part.image{cursor:grab;outline:2px solid #f59e0b}.sr16-crop-badge{position:absolute;background:#111827;color:#fff;padding:5px 9px;border-radius:7px;font:700 11px system-ui;z-index:310;pointer-events:none}.sr16-part[data-selected="1"]{outline:1px solid #7c3aed55}.sr16-part.text{display:flex}.sr16-part.text[contenteditable="true"]{user-select:text;-webkit-user-select:text}.compare-original .sr16-selection,.compare-original .sr16-part,.compare-original .sr16-toolbar{display:none!important}@media print{.sr16-selection,.sr16-guide,.sr16-marquee,.sr16-crop-badge{display:none!important}}`;document.head.appendChild(s)}injectCSS();
function textStyle(n,s={},role){n.style.fontFamily=s.font||'Segoe UI';n.style.fontWeight=s.bold?'900':'700';n.style.fontStyle=s.italic?'italic':'normal';n.style.color=s.color||'#172033';const a=s.align||'center';n.style.textAlign=a;n.style.justifyContent=a==='right'?'flex-end':a==='left'?'flex-start':'center';const v=s.vAlign||'center';n.style.alignItems=v==='top'?'flex-start':v==='bottom'?'flex-end':'center';n.style.lineHeight=role==='NOME'?'1.02':'1';n.style.padding=role==='NOME'?'1px 3px':'1px';n.style.overflow='hidden';n.style.whiteSpace=role==='NOME'?'normal':'nowrap';n.style.overflowWrap=role==='NOME'?'break-word':'normal'}
function fitText(n,role,f){if(n.isContentEditable)return;const base=Number(f.style?.fontSize||20);let lo=Math.max(6,base*(role==='NOME'?.38:.45)),hi=Math.max(base,Math.min(base*1.35,f.h*1.12)),best=lo;for(let i=0;i<14;i++){const m=(lo+hi)/2;n.style.fontSize=m+'px';if(n.scrollWidth<=n.clientWidth+1&&n.scrollHeight<=n.clientHeight+1){best=m;lo=m}else hi=m}n.style.fontSize=best+'px'}
function imageSafe(slot,e,base){const f=A.effectiveField(e,'IMAGEM',base),px=Math.max(2,f.w*.035),py=Math.max(2,f.h*.035);let b={...f,x:f.x+px,y:f.y+py,w:Math.max(16,f.w-px*2),h:Math.max(16,f.h-py*2)};for(const r of ['PRECO_REAIS','PRECO_CENTAVOS','PRECO_RS','UNIDADE']){const q0=slot.fields?.[r];if(!q0)continue;const q=A.effectiveField(e,r,q0);const ix=Math.max(0,Math.min(b.x+b.w,q.x+q.w)-Math.max(b.x,q.x)),iy=Math.max(0,Math.min(b.y+b.h,q.y+q.h)-Math.max(b.y,q.y));if(ix*iy<=0)continue;if(q.x>b.x+b.w/2)b.w=Math.max(16,q.x-b.x-3);else if(q.y>b.y+b.h/2)b.h=Math.max(16,q.y-b.y-3)}return b}
function visualField(ctx){if(ctx.role==='IMAGEM')return imageSafe(ctx.slot,ctx.e,ctx.base);return A.effectiveField(ctx.e,ctx.role,ctx.base)}
function allContexts(){const pg=A.page(),out=[];for(const e of pg.elements||[]){if(!e.slotId)continue;const slot=(pg.templateSlots||[]).find(s=>s.id===e.slotId);if(!slot)continue;for(const [role,base] of Object.entries(slot.fields||{})){if(!A.PART_ROLES.includes(role))continue;const c={k:A.partKey(e.id,role),eid:e.id,role,pg,e,slot,base,edit:A.ensurePart(e,role),product:A.state.products.find(p=>p.id===e.productId)||null};c.field=visualField(c);out.push(c)}}return out}
A.allPartContexts=allContexts;
A.selectionBounds=()=>{const cs=A.selectionContexts().map(c=>({...c,field:visualField(c)}));if(!cs.length)return null;const xs=cs.map(c=>c.field.x),ys=cs.map(c=>c.field.y),rs=cs.map(c=>c.field.x+c.field.w),bs=cs.map(c=>c.field.y+c.field.h);return{x:Math.min(...xs),y:Math.min(...ys),w:Math.max(...rs)-Math.min(...xs),h:Math.max(...bs)-Math.min(...ys)}};
function guidesFor(exclude){const pg=A.page(),xs=[0,pg.width/2,pg.width],ys=[0,pg.height/2,pg.height];for(const c of allContexts()){if(c.edit.hidden||exclude.has(c.k))continue;xs.push(c.field.x,c.field.x+c.field.w/2,c.field.x+c.field.w);ys.push(c.field.y,c.field.y+c.field.h/2,c.field.y+c.field.h)}return{xs,ys}}
function snapMove(box,g,th=5){let dx=0,dy=0,gx=null,gy=null,bd=th+1;for(const target of g.xs)for(const p of [box.x,box.x+box.w/2,box.x+box.w]){const d=Math.abs(target-p);if(d<bd){bd=d;dx=target-p;gx=target}}bd=th+1;for(const target of g.ys)for(const p of [box.y,box.y+box.h/2,box.y+box.h]){const d=Math.abs(target-p);if(d<bd){bd=d;dy=target-p;gy=target}}return{dx,dy,gx,gy}}
function clearGuides(){A.pageNode.querySelectorAll('.sr16-guide').forEach(n=>n.remove())}
function showGuide(kind,v){const g=E('div','sr16-guide '+kind);if(kind==='v')g.style.left=v+'px';else g.style.top=v+'px';A.pageNode.appendChild(g)}
function startMove(ev,ctx,node){if(ctx.edit.locked)return;const current=A.state.proSelection||[],k=ctx.k;if(ev.shiftKey)A.selectPart(ctx.eid,ctx.role,'toggle');else if(!current.includes(k))A.selectPart(ctx.eid,ctx.role,'replace');const cs=A.selectionContexts().filter(c=>!c.edit.locked);if(!cs.length)return;A.snapshot();const scale=Number(A.state.zoom)||1,sx=ev.clientX,sy=ev.clientY,starts={};for(const c of cs)starts[c.k]={dx:Number(c.edit.dx)||0,dy:Number(c.edit.dy)||0,field:visualField(c)};const startBox=A.selectionBounds(),exclude=new Set(cs.map(c=>c.k)),g=guidesFor(exclude);node.setPointerCapture?.(ev.pointerId);const move=m=>{let dx=(m.clientX-sx)/scale,dy=(m.clientY-sy)/scale;const test={x:startBox.x+dx,y:startBox.y+dy,w:startBox.w,h:startBox.h},sn=snapMove(test,g,6);dx+=sn.dx;dy+=sn.dy;clearGuides();if(sn.gx!==null)showGuide('v',sn.gx);if(sn.gy!==null)showGuide('h',sn.gy);for(const c of cs){c.edit.dx=starts[c.k].dx+dx;c.edit.dy=starts[c.k].dy+dy}A.save();A.renderCanvas();A.renderInspector?.()};const up=()=>{document.removeEventListener('pointermove',move,true);document.removeEventListener('pointerup',up,true);clearGuides();A.save();A.emit()};document.addEventListener('pointermove',move,true);document.addEventListener('pointerup',up,true)}
function bindPart(node,ctx){node.dataset.partKey=ctx.k;node.dataset.role=ctx.role;node.dataset.elementId=ctx.eid;node.dataset.selected=(A.state.proSelection||[]).includes(ctx.k)?'1':'0';node.classList.toggle('locked',Boolean(ctx.edit.locked));node.addEventListener('pointerdown',ev=>{if(ev.button!==0)return;ev.preventDefault();ev.stopPropagation();if(A.state.cropKey===ctx.k&&ctx.role==='IMAGEM'){startCropDrag(ev,ctx,node);return}startMove(ev,ctx,node)});node.addEventListener('click',ev=>{ev.stopPropagation();if(ev.shiftKey)A.selectPart(ctx.eid,ctx.role,'toggle');else if(!(A.state.proSelection||[]).includes(ctx.k))A.selectPart(ctx.eid,ctx.role,'replace')});node.addEventListener('dblclick',ev=>{ev.preventDefault();ev.stopPropagation();if(ctx.role==='IMAGEM'){A.state.cropKey=ctx.k;A.selectPart(ctx.eid,ctx.role,'replace');A.save();A.renderCanvas();return}startTextEdit(node,ctx)});if(ctx.role==='IMAGEM')node.addEventListener('wheel',ev=>{if(A.state.cropKey!==ctx.k)return;ev.preventDefault();A.snapshot();ctx.edit.imageScale=Math.max(.2,Math.min(5,(Number(ctx.edit.imageScale)||1)+(ev.deltaY<0?.08:-.08)));A.save();A.renderCanvas()},{passive:false})}
function startCropDrag(ev,ctx,node){if(ctx.edit.locked)return;A.snapshot();const sx=ev.clientX,sy=ev.clientY,fx=Number(ctx.edit.focusX??50),fy=Number(ctx.edit.focusY??50),r=node.getBoundingClientRect();const move=m=>{ctx.edit.focusX=Math.max(0,Math.min(100,fx+(m.clientX-sx)/Math.max(1,r.width)*100));ctx.edit.focusY=Math.max(0,Math.min(100,fy+(m.clientY-sy)/Math.max(1,r.height)*100));A.save();A.renderCanvas()};const up=()=>{document.removeEventListener('pointermove',move,true);document.removeEventListener('pointerup',up,true);A.save();A.emit()};document.addEventListener('pointermove',move,true);document.addEventListener('pointerup',up,true)}
function startTextEdit(node,ctx){if(ctx.edit.locked)return;A.state.cropKey=null;A.selectPart(ctx.eid,ctx.role,'replace');node.contentEditable='true';node.classList.add('editing-text');node.focus();const range=document.createRange();range.selectNodeContents(node);const sel=getSelection();sel.removeAllRanges();sel.addRange(range);const finish=()=>{node.removeEventListener('blur',finish);node.contentEditable='false';node.classList.remove('editing-text');A.snapshot();A.commitRoleText(ctx,node.textContent);A.renderCanvas()};node.addEventListener('blur',finish);node.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();node.textContent=val(ctx.role,ctx.product);node.blur()}else if(e.key==='Enter'&&ctx.role!=='NOME'){e.preventDefault();node.blur()}},{once:false})}
function renderPart(ctx){const f=visualField(ctx),edit=ctx.edit,p=ctx.product;if(edit.hidden)return;if(ctx.role==='IMAGEM'){if(!p?.image)return;const wrap=E('div','sr16-part image');pos(wrap,f);wrap.style.zIndex=String(edit.z??8);wrap.style.opacity=String(edit.opacity??1);wrap.style.transform=`rotate(${Number(edit.rotation)||0}deg)`;wrap.style.borderRadius=ctx.base.autoDetected?Math.min(24,Math.max(7,Math.min(f.w,f.h)*.1))+'px':'0';const img=E('img');img.src=p.image;img.alt=p.name||'Produto';img.style.objectFit=edit.fit||ctx.base.fit||ctx.base.style?.fit||'contain';img.style.objectPosition=(edit.focusX??50)+'% '+(edit.focusY??50)+'%';img.style.transform=`scaleX(${edit.flipX?-1:1}) scaleY(${edit.flipY?-1:1}) scale(${Number(edit.imageScale)||1})`;img.style.transformOrigin=img.style.objectPosition;wrap.appendChild(img);A.pageNode.appendChild(wrap);bindPart(wrap,ctx)}else{const n=E('div','sr16-part text',val(ctx.role,p));pos(n,f);n.style.zIndex=String(edit.z??45);n.style.opacity=String(edit.opacity??1);n.style.transform=`rotate(${Number(edit.rotation)||0}deg)`;textStyle(n,f.style,ctx.role);A.pageNode.appendChild(n);fitText(n,ctx.role,f);bindPart(n,ctx);if(document.fonts?.ready)document.fonts.ready.then(()=>fitText(n,ctx.role,visualField(ctx)))}}
function renderSelection(){const cs=A.selectionContexts();if(!cs.length)return;const b=A.selectionBounds();if(!b)return;const box=E('div','sr16-selection'+(cs.length>1?' multi':''));pos(box,b);A.pageNode.appendChild(box);for(const dir of ['nw','n','ne','e','se','s','sw','w']){const h=E('span','sr16-handle '+dir);h.dataset.dir=dir;box.appendChild(h);h.addEventListener('pointerdown',ev=>startResize(ev,dir,b))}const line=E('span','sr16-rotate-line'),rot=E('span','sr16-rotate');box.append(line,rot);rot.addEventListener('pointerdown',ev=>startRotate(ev,b));if(A.state.cropKey&&cs.length===1&&cs[0].k===A.state.cropKey){A.pageNode.classList.add('sr16-crop');const badge=E('div','sr16-crop-badge','Recorte: arraste a foto · roda do mouse = zoom');badge.style.left=Math.max(0,b.x)+'px';badge.style.top=Math.max(0,b.y-32)+'px';A.pageNode.appendChild(badge)}else A.pageNode.classList.remove('sr16-crop')}
function startResize(ev,dir,startBox){ev.preventDefault();ev.stopPropagation();const cs=A.selectionContexts().filter(c=>!c.edit.locked);if(!cs.length)return;A.snapshot();const scale=Number(A.state.zoom)||1,sx=ev.clientX,sy=ev.clientY,startFields={};for(const c of cs)startFields[c.k]={...visualField(c)};const ratio=startBox.w/startBox.h;const move=m=>{let dx=(m.clientX-sx)/scale,dy=(m.clientY-sy)/scale,b={...startBox};if(dir.includes('e'))b.w=Math.max(8,startBox.w+dx);if(dir.includes('s'))b.h=Math.max(8,startBox.h+dy);if(dir.includes('w')){b.x=startBox.x+dx;b.w=Math.max(8,startBox.w-dx)}if(dir.includes('n')){b.y=startBox.y+dy;b.h=Math.max(8,startBox.h-dy)}if(m.shiftKey&&dir.length===2){if(Math.abs(dx)>Math.abs(dy))b.h=b.w/ratio;else b.w=b.h*ratio}A.resizeSelectionTo(b,startBox,startFields);A.save();A.renderCanvas();A.renderInspector?.()};const up=()=>{document.removeEventListener('pointermove',move,true);document.removeEventListener('pointerup',up,true);A.save();A.emit()};document.addEventListener('pointermove',move,true);document.addEventListener('pointerup',up,true)}
function startRotate(ev,b){ev.preventDefault();ev.stopPropagation();const cs=A.selectionContexts().filter(c=>!c.edit.locked);if(!cs.length)return;A.snapshot();const rect=A.pageNode.getBoundingClientRect(),scale=Number(A.state.zoom)||1,cx=rect.left+(b.x+b.w/2)*scale,cy=rect.top+(b.y+b.h/2)*scale,start=Math.atan2(ev.clientY-cy,ev.clientX-cx)*180/Math.PI,rots={};for(const c of cs)rots[c.k]=Number(c.edit.rotation)||0;const move=m=>{let d=Math.atan2(m.clientY-cy,m.clientX-cx)*180/Math.PI-start;if(m.shiftKey)d=Math.round(d/15)*15;for(const c of cs)c.edit.rotation=rots[c.k]+d;A.save();A.renderCanvas();A.renderInspector?.()};const up=()=>{document.removeEventListener('pointermove',move,true);document.removeEventListener('pointerup',up,true);A.save();A.emit()};document.addEventListener('pointermove',move,true);document.addEventListener('pointerup',up,true)}
function marquee(ev){if(ev.button!==0||ev.target!==A.pageNode)return;const rect=A.pageNode.getBoundingClientRect(),scale=Number(A.state.zoom)||1,sx=(ev.clientX-rect.left)/scale,sy=(ev.clientY-rect.top)/scale,mq=E('div','sr16-marquee');A.pageNode.appendChild(mq);const move=m=>{const x=(m.clientX-rect.left)/scale,y=(m.clientY-rect.top)/scale,b={x:Math.min(sx,x),y:Math.min(sy,y),w:Math.abs(x-sx),h:Math.abs(y-sy)};pos(mq,b)};const up=m=>{document.removeEventListener('pointermove',move,true);document.removeEventListener('pointerup',up,true);const x=(m.clientX-rect.left)/scale,y=(m.clientY-rect.top)/scale,b={x:Math.min(sx,x),y:Math.min(sy,y),w:Math.abs(x-sx),h:Math.abs(y-sy)},hits=[];for(const c of allContexts()){if(c.edit.hidden)continue;const f=c.field;if(Math.max(b.x,f.x)<Math.min(b.x+b.w,f.x+f.w)&&Math.max(b.y,f.y)<Math.min(b.y+b.h,f.y+f.h))hits.push(c.k)}mq.remove();A.state.proSelection=hits;const first=hits[0]?A.partContext(hits[0]):null;A.state.selected=first?.eid||null;A.state.selectedPart=first?.role||null;A.save();A.emit()};document.addEventListener('pointermove',move,true);document.addEventListener('pointerup',up,true)}
A.pageNode.addEventListener('pointerdown',marquee,true);
A.renderCanvas=()=>{const pg=A.page();if(!pg?.backgroundUrl)return fallback();A.pageNode.replaceChildren();A.pageNode.style.width=pg.width+'px';A.pageNode.style.height=pg.height+'px';A.zoomNode.style.transform='scale('+A.state.zoom+')';A.zoomNode.style.marginBottom='-'+(pg.height*(1-A.state.zoom))+'px';const bg=E('img','tpl-img');bg.src=pg.backgroundUrl;bg.alt='Design original';bg.style.objectFit='fill';bg.style.pointerEvents='none';bg.style.zIndex='1';pos(bg,{x:0,y:0,w:pg.width,h:pg.height});A.pageNode.appendChild(bg);if(A.state.compareOriginal)return;const filled=new Set((pg.elements||[]).filter(e=>e.slotId).map(e=>e.slotId));for(const s of pg.templateSlots||[])if(!filled.has(s.id)){const x=E('div','slot-empty','PRODUTO '+s.index);x.style.zIndex='70';pos(x,s);A.pageNode.appendChild(x)}for(const c of allContexts())renderPart(c);renderSelection()};
console.info('[SR Studio] Beta 16 canvas estilo Canva ativo');
})();

(() => {
'use strict';
const A=window.SR11,E=A.E;if(!A||A.__BETA16_UI__)return;A.__BETA16_UI__=true;
function B(label,fn,cls='btn'){const b=E('button',cls,label);b.type='button';b.addEventListener('click',ev=>{ev.preventDefault();ev.stopPropagation();fn()});return b}
function setPart(ctx,patch){if(!ctx)return;A.snapshot();Object.assign(ctx.edit,patch);A.commit()}
function selected(){return A.selectionContexts?.()||[]}
function selectedOne(){const x=selected();return x.length===1?x[0]:null}
function currentProduct(){const e=A.selectedElement?.();return e?A.state.products.find(p=>p.id===e.productId):null}
function css(){if(document.getElementById('sr16-ui-css'))return;const s=document.createElement('style');s.id='sr16-ui-css';s.textContent=`.sr16-float{position:fixed;display:flex;align-items:center;gap:5px;padding:6px;background:#fff;border:1px solid #d9dce5;border-radius:9px;box-shadow:0 8px 28px #11182722;z-index:2147483200;font:600 12px system-ui}.sr16-float button,.sr16-float select,.sr16-float input{height:30px;border:1px solid #d8dce7;background:#fff;border-radius:6px;padding:0 8px;font:600 12px system-ui}.sr16-float button:hover{background:#f5f3ff}.sr16-float .icon{width:30px;padding:0}.sr16-float .primary{background:#7c3aed;color:#fff;border-color:#7c3aed}.sr16-float .sep{width:1px;height:22px;background:#e5e7eb;margin:0 2px}.sr16-menu{position:fixed;min-width:190px;background:#fff;border:1px solid #d9dce5;border-radius:10px;box-shadow:0 12px 36px #11182733;padding:6px;z-index:2147483300;font:600 12px system-ui}.sr16-menu button{width:100%;text-align:left;border:0;background:transparent;padding:8px 10px;border-radius:6px}.sr16-menu button:hover{background:#f5f3ff}.sr16-panel-title{font-size:11px;font-weight:900;text-transform:uppercase;letter-spacing:.05em;color:#687386;margin:12px 0 6px}.sr16-grid4{display:grid;grid-template-columns:1fr 1fr;gap:6px}.sr16-grid4 label{font-size:10px;font-weight:800;color:#667085}.sr16-grid4 input,.sr16-grid4 select{width:100%;box-sizing:border-box;padding:7px;border:1px solid #d9dfeb;border-radius:7px}.sr16-btnrow{display:flex;gap:5px;flex-wrap:wrap;margin:7px 0}.sr16-btnrow button{flex:1;min-width:48px}.sr16-layer{display:grid;grid-template-columns:1fr 32px 32px;gap:4px;align-items:center;padding:5px 0;border-bottom:1px solid #edf0f5}.sr16-layer.active .name{background:#ede9fe;border-color:#8b5cf6}.sr16-layer .name{text-align:left}.sr16-hint{font-size:10px;line-height:1.35;color:#667085;background:#f8fafc;border:1px solid #e5e7eb;border-radius:7px;padding:7px;margin-top:7px}`;document.head.appendChild(s)}css();
let float=null,menu=null;
function closeMenu(){menu?.remove();menu=null}
function selectionClientRect(){const b=A.selectionBounds?.();if(!b)return null;const r=A.pageNode.getBoundingClientRect(),z=Number(A.state.zoom)||1;return{left:r.left+b.x*z,top:r.top+b.y*z,width:b.w*z,height:b.h*z,bottom:r.top+(b.y+b.h)*z,right:r.left+(b.x+b.w)*z}}
function icon(label,title,fn){const b=B(label,fn,'icon');b.title=title;return b}
function fontControl(bar,c){if(c.role==='IMAGEM')return;const sel=E('select');const families=['Segoe UI',...(A.state.fonts||[]).map(f=>f.family)].filter((x,i,a)=>a.indexOf(x)===i);for(const f of families){const o=E('option','',f);o.value=f;if(f===(c.edit.font||c.base.style?.font||'Segoe UI'))o.selected=true;sel.appendChild(o)}sel.addEventListener('change',()=>setPart(c,{font:sel.value}));bar.appendChild(sel);const size=E('input');size.type='number';size.min='6';size.max='240';size.style.width='58px';size.value=Math.round(c.edit.fontSize||c.base.style?.fontSize||20);size.title='Tamanho da fonte';size.addEventListener('change',()=>setPart(c,{fontSize:Number(size.value)||undefined}));bar.appendChild(size);bar.append(icon('B','Negrito',()=>setPart(c,{bold:!Boolean(c.edit.bold??c.base.style?.bold)})),icon('I','Itálico',()=>setPart(c,{italic:!Boolean(c.edit.italic??c.base.style?.italic)})),icon('≡','Alinhar',()=>{const cur=c.edit.align||c.base.style?.align||'center';setPart(c,{align:cur==='left'?'center':cur==='center'?'right':'left'})}));const color=E('input');color.type='color';color.value=c.edit.color||c.base.style?.color||'#172033';color.title='Cor';color.addEventListener('change',()=>setPart(c,{color:color.value}));bar.appendChild(color)}
function imageControls(bar,c){if(c.role!=='IMAGEM')return;bar.append(icon('⌗','Recortar / enquadrar',()=>{A.state.cropKey=A.state.cropKey===c.k?null:c.k;A.save();A.renderCanvas();renderFloat()}),icon('↔','Virar horizontal',()=>A.flipSelection('x')),icon('↕','Virar vertical',()=>A.flipSelection('y')));const fit=E('select');for(const [v,t] of [['contain','Inteira'],['cover','Preencher'],['fill','Esticar']]){const o=E('option','',t);o.value=v;if(v===(c.edit.fit||c.base.fit||c.base.style?.fit||'contain'))o.selected=true;fit.appendChild(o)}fit.addEventListener('change',()=>setPart(c,{fit:fit.value}));bar.appendChild(fit)}
function renderFloat(){float?.remove();float=null;const cs=selected();if(!cs.length)return;const r=selectionClientRect();if(!r)return;float=E('div','sr16-float');const one=cs.length===1?cs[0]:null;if(one)fontControl(float,one),imageControls(float,one);if(float.childNodes.length)float.appendChild(E('span','sep'));float.append(icon('⧉','Duplicar produto',()=>A.duplicateSelectionProduct()),icon(cs.every(c=>c.edit.locked)?'🔒':'🔓','Bloquear / desbloquear',()=>A.lockSelection()),icon('↓','Enviar para trás',()=>A.layerSelection('back')),icon('↑','Trazer para frente',()=>A.layerSelection('front')));if(cs.length>1){float.append(icon('⊞','Agrupar',()=>A.groupSelection()),icon('⊟','Desagrupar',()=>A.ungroupSelection()))}const more=icon('•••','Mais',()=>{});more.onclick=ev=>{ev.stopPropagation();openMenu(ev.clientX,ev.clientY)};float.appendChild(more);document.body.appendChild(float);const w=float.offsetWidth,h=float.offsetHeight,left=Math.max(8,Math.min(innerWidth-w-8,r.left+r.width/2-w/2)),top=r.top-h-10>8?r.top-h-10:Math.min(innerHeight-h-8,r.bottom+10);float.style.left=left+'px';float.style.top=top+'px'}
function openMenu(x,y){closeMenu();menu=E('div','sr16-menu');const items=[['Duplicar',()=>A.duplicateSelectionProduct()],['Agrupar',()=>A.groupSelection()],['Desagrupar',()=>A.ungroupSelection()],['Bloquear/Desbloquear',()=>A.lockSelection()],['Trazer para frente',()=>A.layerSelection('front')],['Avançar uma camada',()=>A.layerSelection('forward')],['Recuar uma camada',()=>A.layerSelection('backward')],['Enviar para trás',()=>A.layerSelection('back')],['Ocultar elemento',()=>A.hideSelection(true)],['Resetar ajustes',()=>{for(const c of selected()){A.state.selected=c.eid;A.state.selectedPart=c.role;A.resetSelectedPart()}A.emit()}]];for(const [t,fn] of items)menu.appendChild(B(t,()=>{fn();closeMenu()},''));document.body.appendChild(menu);menu.style.left=Math.min(x,innerWidth-menu.offsetWidth-8)+'px';menu.style.top=Math.min(y,innerHeight-menu.offsetHeight-8)+'px'}
document.addEventListener('pointerdown',ev=>{if(menu&&!menu.contains(ev.target))closeMenu()});
A.pageNode.addEventListener('contextmenu',ev=>{const part=ev.target.closest('.sr16-part');if(!part)return;ev.preventDefault();const k=part.dataset.partKey,c=A.partContext(k);if(c&&!A.state.proSelection.includes(k))A.selectPart(c.eid,c.role,'replace');openMenu(ev.clientX,ev.clientY)});
function numField(label,value,change,step='1'){const wrap=E('label');wrap.textContent=label;const inp=E('input');inp.type='number';inp.step=step;inp.value=Number.isFinite(Number(value))?Math.round(Number(value)*100)/100:'';inp.addEventListener('change',()=>change(Number(inp.value)||0));wrap.appendChild(inp);return wrap}
function selectField(label,value,items,change){const wrap=E('label');wrap.textContent=label;const s=E('select');for(const [v,t] of items){const o=E('option','',t);o.value=v;if(String(v)===String(value))o.selected=true;s.appendChild(o)}s.addEventListener('change',()=>change(s.value));wrap.appendChild(s);return wrap}
function setBoxDimension(kind,v){const cs=selected(),b=A.selectionBounds();if(!cs.length||!b)return;A.snapshot();if(kind==='x'){A.moveSelection(v-b.x,0,false);A.commit()}else if(kind==='y'){A.moveSelection(0,v-b.y,false);A.commit()}else{const nb={...b};nb[kind]=Math.max(8,v);const starts={};for(const c of cs)starts[c.k]={...c.field};A.resizeSelectionTo(nb,b,starts);A.commit()}}
function productInspector(host){const e=A.selectedElement?.(),p=currentProduct();if(!e||!p)return;host.appendChild(E('div','sr16-panel-title','Produto'));const make=A.makeField;const name=make(host,'Nome comercial',p.name),price=make(host,'Preço',p.price),app=make(host,'Preço APP',p.app),unit=make(host,'Unidade',{current:p.unit||'UN',items:['UN','KG','CX','PCT','BDJ','DZ','LT'].map(x=>({value:x,label:x}))},'select'),limit=make(host,'Limite por CPF',p.limit),cat=make(host,'Categoria',p.category||'SEM CATEGORIA');const save=()=>{A.snapshot();p.name=name.value.trim();p.price=A.money(price.value);p.app=A.money(app.value);p.unit=unit.value;p.limit=limit.value.trim();p.category=cat.value.trim()||'SEM CATEGORIA';A.commit()};for(const i of [name,price,app,unit,limit,cat])i.addEventListener('change',save)}
function positionPanel(host){const cs=selected();if(!cs.length)return;const b=A.selectionBounds(),one=cs.length===1?cs[0]:null;host.appendChild(E('div','sr16-panel-title',cs.length>1?'Posição · '+cs.length+' elementos':'Posição · '+A.partLabel(one.role)));const grid=E('div','sr16-grid4');grid.append(numField('X',b.x,v=>setBoxDimension('x',v)),numField('Y',b.y,v=>setBoxDimension('y',v)),numField('Largura',b.w,v=>setBoxDimension('w',v)),numField('Altura',b.h,v=>setBoxDimension('h',v)));host.appendChild(grid);const grid2=E('div','sr16-grid4');const rot=one?one.edit.rotation||0:0,op=one?one.edit.opacity??1:1;grid2.append(numField('Rotação °',rot,v=>A.setSelectionRotation(v)),numField('Opacidade %',op*100,v=>A.setSelectionOpacity(v/100)));if(one?.role==='IMAGEM'){grid2.append(numField('Zoom imagem',one.edit.imageScale??1,v=>setPart(one,{imageScale:Math.max(.2,Math.min(5,v||1))}),'.05'),selectField('Encaixe',one.edit.fit||one.base.fit||'contain',[['contain','Mostrar inteira'],['cover','Preencher'],['fill','Esticar']],v=>setPart(one,{fit:v})))}host.appendChild(grid2);const ar=E('div','sr16-btnrow');for(const [t,m] of [['⟸','left'],['↔','center'],['⟹','right'],['⤒','top'],['↕','middle'],['⤓','bottom']])ar.appendChild(B(t,()=>A.alignSelection(m)));host.appendChild(ar);if(cs.length>=3){const d=E('div','sr16-btnrow');d.append(B('Distribuir H',()=>A.distributeSelection('x')),B('Distribuir V',()=>A.distributeSelection('y')));host.appendChild(d)}const actions=E('div','sr16-btnrow');actions.append(B(cs.every(c=>c.edit.locked)?'Desbloquear':'Bloquear',()=>A.lockSelection()),B('Frente',()=>A.layerSelection('front')),B('Trás',()=>A.layerSelection('back')));host.appendChild(actions);host.appendChild(E('div','sr16-hint','Shift + clique seleciona várias partes. Arraste a seleção inteira, use as 8 alças para redimensionar e a alça superior para girar. Duplo clique em texto edita direto; duplo clique na imagem entra no recorte.'))}
function layerPanel(host){const e=A.selectedElement?.(),slot=A.selectedSlot?.();if(!e||!slot)return;host.appendChild(E('div','sr16-panel-title','Camadas'));const roles=A.PART_ROLES.filter(r=>slot.fields?.[r]);roles.sort((a,b)=>{const ca=A.partContext(A.partKey(e.id,a)),cb=A.partContext(A.partKey(e.id,b));return(Number(cb?.edit.z??(b==='IMAGEM'?8:45))-Number(ca?.edit.z??(a==='IMAGEM'?8:45)))});for(const role of roles){const c=A.partContext(A.partKey(e.id,role)),row=E('div','sr16-layer'+(A.state.proSelection.includes(c.k)?' active':''));const name=B((c.edit.hidden?'○ ':'● ')+A.partLabel(role),()=>A.selectPart(e.id,role,'replace'),'name btn');const eye=B(c.edit.hidden?'👁':'◉',()=>{c.edit.hidden=!c.edit.hidden;A.commit()},'btn');const lock=B(c.edit.locked?'🔒':'🔓',()=>{c.edit.locked=!c.edit.locked;A.commit()},'btn');row.append(name,eye,lock);host.appendChild(row)}}
A.renderInspector=()=>{A.inspectorNode.replaceChildren();A.issueNode.replaceChildren();productInspector(A.inspectorNode);positionPanel(A.inspectorNode);layerPanel(A.inspectorNode);const pg=A.page(),issues=A.validate().filter(x=>x.message.startsWith(pg.name+':')).slice(0,6);for(const issue of issues)A.issueNode.appendChild(E('div','issue '+issue.severity,issue.message));renderFloat()};
const oldRenderAll=A.renderAll;A.renderAll=()=>{A.renderCategories();A.renderProducts();A.renderPages();A.renderCanvas();A.renderKPIs();A.renderInspector()};A.listeners?.delete?.(oldRenderAll);A.onChange(A.renderAll);
function shortcut(ev){if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName)||document.activeElement?.isContentEditable)return;const ctrl=ev.ctrlKey||ev.metaKey,key=ev.key;if(key==='Escape'){ev.preventDefault();if(A.state.cropKey){A.state.cropKey=null;A.renderCanvas();renderFloat()}else A.clearProSelection();return}if(key==='Delete'||key==='Backspace'){if(selected().length){ev.preventDefault();ev.stopImmediatePropagation();A.snapshot();A.hideSelection(true)}return}if(ctrl&&key.toLowerCase()==='g'){ev.preventDefault();ev.stopImmediatePropagation();ev.shiftKey?A.ungroupSelection():A.groupSelection();return}if(ctrl&&key.toLowerCase()==='d'){ev.preventDefault();A.duplicateSelectionProduct();return}if(ctrl&&(key===']'||key==='[')){ev.preventDefault();if(key===']')A.layerSelection(ev.altKey?'front':'forward');else A.layerSelection(ev.altKey?'back':'backward');return}if(key===','||key==='.'){if(selected().length){ev.preventDefault();const step=ev.shiftKey?15:1;A.snapshot();for(const c of selected())c.edit.rotation=(Number(c.edit.rotation)||0)+(key==='.'?step:-step);A.commit()}return}const arrows={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]};if(arrows[key]&&selected().length){ev.preventDefault();ev.stopImmediatePropagation();const step=ev.shiftKey?10:1,[x,y]=arrows[key];A.snapshot();A.moveSelection(x*step,y*step,true);return}if(key==='Tab'){const all=A.allPartContexts?.().filter(c=>!c.edit.hidden)||[];if(!all.length)return;ev.preventDefault();const cur=(A.state.proSelection||[])[0],i=Math.max(0,all.findIndex(c=>c.k===cur)),n=all[(i+(ev.shiftKey?-1:1)+all.length)%all.length];A.selectPart(n.eid,n.role,'replace')}}
document.addEventListener('keydown',shortcut,true);
window.addEventListener('resize',renderFloat);A.centerNode.addEventListener('scroll',renderFloat,{passive:true});
A.renderAll();
console.info('[SR Studio] Beta 16 UI estilo Canva ativa');
})();
