(() => {
'use strict';
const A=window.SR11,E=A.E;if(!A||A.__BETA16_UI__)return;A.__BETA16_UI__=true;
function B(label,fn,cls='btn'){const b=E('button',cls,label);b.type='button';b.addEventListener('click',ev=>{ev.preventDefault();ev.stopPropagation();fn()});return b}
function setPart(ctx,patch){if(!ctx)return;A.snapshot();Object.assign(ctx.edit,patch);A.commit()}
function selected(){return A.selectionContexts?.()||[]}
function selectedOne(){const x=selected();return x.length===1?x[0]:null}
function currentProduct(){const e=A.selectedElement?.();return e?A.state.products.find(p=>p.id===e.productId):null}
function css(){if(document.getElementById('sr16-ui-css'))return;const s=document.createElement('style');s.id='sr16-ui-css';s.textContent=`.sr16-float{position:fixed;display:flex;align-items:center;gap:5px;padding:6px;background:#fff;border:1px solid #d9dce5;border-radius:9px;box-shadow:0 8px 28px #11182722;z-index:2147483200;font:600 12px system-ui}.sr16-float button,.sr16-float select,.sr16-float input{height:30px;border:1px solid #d8dce7;background:#fff;border-radius:6px;padding:0 8px;font:600 12px system-ui}.sr16-float button:hover{background:#f5f3ff}.sr16-float .icon{width:30px;padding:0}.sr16-float .primary{background:#7c3aed;color:#fff;border-color:#7c3aed}.sr16-float .sep{width:1px;height:22px;background:#e5e7eb;margin:0 2px}.sr16-menu{position:fixed;min-width:190px;background:#fff;border:1px solid #d9dce5;border-radius:10px;box-shadow:0 12px 36px #11182733;padding:6px;z-index:2147483300;font:600 12px system-ui}.sr16-menu button{width:100%;text-align:left;border:0;background:transparent;padding:8px 10px;border-radius:6px}.sr16-menu button:hover{background:#f5f3ff}.sr16-panel-title{font-size:11px;font-weight:900;text-transform:uppercase;letter-spacing:.05em;color:#687386;margin:12px 0 6px}.sr16-grid4{display:grid;grid-template-columns:1fr 1fr;gap:6px}.sr16-grid4 label{font-size:10px;font-weight:800;color:#667085}.sr16-grid4 input,.sr16-grid4 select{width:100%;box-sizing:border-box;padding:7px;border:1px solid #d9dfeb;border-radius:7px}.sr16-btnrow{display:flex;gap:5px;flex-wrap:wrap;margin:7px 0}.sr16-btnrow button{flex:1;min-width:48px}.sr16-layer{display:grid;grid-template-columns:1fr 32px 32px;gap:4px;align-items:center;padding:5px 0;border-bottom:1px solid #edf0f5}.sr16-layer.active .name{background:#ede9fe;border-color:#8b5cf6}.sr16-layer .name{text-align:left}.sr16-hint{font-size:10px;line-height:1.35;color:#667085;background:#f8fafc;border:1px solid #e5e7eb;border-radius:7px;padding:7px;margin-top:7px}`;document.head.appendChild(s)}css();
let float=null,menu=null;
function closeMenu(){menu?.remove();menu=null}
function selectionClientRect(){const b=A.selectionBounds?.();if(!b)return null;const r=A.pageNode.getBoundingClientRect(),z=Number(A.state.zoom)||1;return{left:r.left+b.x*z,top:r.top+b.y*z,width:b.w*z,height:b.h*z,bottom:r.top+(b.y+b.h)*z,right:r.left+(b.x+b.w)*z}}
function icon(label,title,fn){const b=B(label,fn,'icon');b.title=title;return b}
function fontControl(bar,c){if(c.role==='IMAGEM')return;const sel=E('select');const families=['Segoe UI',...(A.state.fonts||[]).map(f=>f.family)].filter((x,i,a)=>a.indexOf(x)===i);for(const f of families){const o=E('option','',f);o.value=f;if(f===(c.edit.font||c.base.style?.font||'Segoe UI'))o.selected=true;sel.appendChild(o)}sel.addEventListener('change',()=>setPart(c,{font:sel.value}));bar.appendChild(sel);const size=E('input');size.type='number';size.min='6';size.max='240';size.style.width='58px';size.value=Math.round(c.edit.fontSize||c.base.style?.fontSize||20);size.title='Tamanho da fonte';size.addEventListener('change',()=>setPart(c,{fontSize:Number(size.value)||undefined}));bar.appendChild(size);bar.append(icon('B','Negrito',()=>setPart(c,{bold:!Boolean(c.edit.bold??c.base.style?.bold)})),icon('I','Itálico',()=>setPart(c,{italic:!Boolean(c.edit.italic??c.base.style?.italic)})),icon('≡','Alinhar',()=>{const cur=c.edit.align||c.base.style?.align||'center';setPart(c,{align:cur==='left'?'center':cur==='center'?'right':'left'})}));const color=E('input');color.type='color';color.value=c.edit.color||c.base.style?.color||'#172033';color.title='Cor';color.addEventListener('change',()=>setPart(c,{color:color.value}));bar.appendChild(color)}
function imageControls(bar,c){if(c.role!=='IMAGEM')return;bar.append(icon('⌗','Recortar / enquadrar',()=>{A.state.cropKey=A.state.cropKey===c.k?null:c.k;A.save();A.renderCanvas();renderFloat()}),icon('↔','Virar horizontal',()=>A.flipSelection('x')),icon('↕','Virar vertical',()=>A.flipSelection('y')));const fit=E('select');for(const [v,t] of [['contain','Inteira'],['cover','Preencher'],['fill','Esticar']]){const o=E('option','',t);o.value=v;if(v===(c.edit.fit||c.base.fit||c.base.style?.fit||'contain'))o.selected=true;fit.appendChild(o)}fit.addEventListener('change',()=>setPart(c,{fit:fit.value}));bar.appendChild(fit)}
function renderFloat(){float?.remove();float=null;const cs=selected();if(!cs.length)return;const r=selectionClientRect();if(!r)return;float=E('div','sr16-float');const one=cs.length===1?cs[0]:null;if(one)fontControl(float,one),imageControls(float,one);if(float.childNodes.length)float.appendChild(E('span','sep'));float.append(icon('⧉','Duplicar produto',()=>A.duplicateSelectionProduct()),icon(cs.every(c=>c.edit.locked)?'🔒':'🔓','Bloquear / desbloquear',()=>A.lockSelection()),icon('↓','Enviar para trás',()=>A.layerSelection('back')),icon('↑','Trazer para frente',()=>A.layerSelection('front')));if(cs.length>1){float.append(icon('⊞','Agrupar',()=>A.groupSelection()),icon('⊟','Desagrupar',()=>A.ungroupSelection()))}const more=icon('•••','Mais',()=>{});more.onclick=ev=>{ev.stopPropagation();openMenu(ev.clientX,ev.clientY)};float.appendChild(more);document.body.appendChild(float);const w=float.offsetWidth,h=float.offsetHeight,left=Math.max(8,Math.min(innerWidth-w-8,r.left+r.width/2-w/2)),top=r.top-h-10>8?r.top-h-10:Math.min(innerHeight-h-8,r.bottom+10);float.style.left=left+'px';float.style.top=top+'px'}
function openMenu(x,y){closeMenu();menu=E('div','sr16-menu');const items=[['Duplicar',()=>A.duplicateSelectionProduct()],['Agrupar',()=>A.groupSelection()],['Desagrupar',()=>A.ungroupSelection()],['Bloquear/Desbloquear',()=>A.lockSelection()],['Trazer para frente',()=>A.layerSelection('front')],['Avançar uma camada',()=>A.layerSelection('forward')],['Recuar uma camada',()=>A.layerSelection('backward')],['Enviar para trás',()=>A.layerSelection('back')],['Ocultar elemento',()=>A.hideSelection(true)],['Resetar ajustes',()=>{for(const c of selected()){A.state.selected=c.eid;A.state.selectedPart=c.role;A.resetSelectedPart()}A.emit()}]];for(const [t,fn] of items)menu.appendChild(B(t,()=>{fn();closeMenu()},''));document.body.appendChild(menu);menu.style.left=Math.min(x,innerWidth-menu.offsetWidth-8)+'px';menu.style.top=Math.min(y,innerHeight-menu.offsetHeight-8)+'px'}
document.addEventListener('pointerdown',ev=>{if(menu&&!menu.contains(ev.target))closeMenu()});
A.pageNode.addEventListener('contextmenu',ev=>{const part=ev.target.closest('.sr16-part');if(!part)return;ev.preventDefault();const k=part.dataset.partKey,c=A.partContext(k);if(c&&!A.state.proSelection.includes(k))A.selectPart(c.eid,c.role,'replace');openMenu(ev.clientX,ev.clientY)});
function numField(label,value,change,step='1'){const wrap=E('label');wrap.textContent=label;const inp=E('input');inp.type='number';inp.step=step;inp.value=Number.isFinite(Number(value))?Math.round(Number(value)*100)/100:'';inp.addEventListener('change',()=>change(Number(inp.value)||0));wrap.appendChild(inp);return wrap}
function selectField(label,value,items,change){const wrap=E('label');wrap.textContent=label;const s=E('select');for(const [v,t] of items){const o=E('option','',t);o.value=v;if(String(v)===String(value))o.selected=true;s.appendChild(o)}s.addEventListener('change',()=>change(s.value));wrap.appendChild(s);return wrap}
function setBoxDimension(kind,v){const cs=selected(),b=A.selectionBounds();if(!cs.length||!b)return;A.snapshot();if(kind==='x'){A.moveSelection(v-b.x,0,false);A.commit()}else if(kind==='y'){A.moveSelection(0,v-b.y,false);A.commit()}else{const nb={...b};nb[kind]=Math.max(8,v);const starts={};for(const c of cs)starts[c.k]={...c.field};A.resizeSelectionTo(nb,b,starts);A.commit()}}
function productInspector(host){const e=A.selectedElement?.(),p=currentProduct();if(!e||!p)return;host.appendChild(E('div','sr16-panel-title','Produto'));const make=A.makeField;const name=make(host,'Nome comercial',p.name),price=make(host,'Preço',p.price),app=make(host,'Preço APP',p.app),unit=make(host,'Unidade',{current:p.unit||'UN',items:['UN','KG','CX','PCT','BDJ','DZ','LT'].map(x=>({value:x,label:x}))},'select'),limit=make(host,'Limite por CPF',p.limit),cat=make(host,'Categoria',p.category||'SEM CATEGORIA');const save=()=>{A.snapshot();p.name=name.value.trim();p.price=A.money(price.value);p.app=A.money(app.value);p.unit=unit.value;p.limit=limit.value.trim();p.category=cat.value.trim()||'SEM CATEGORIA';A.commit()};for(const i of [name,price,app,unit,limit,cat])i.addEventListener('change',save)}
function positionPanel(host){const cs=selected();if(!cs.length)return;const b=A.selectionBounds(),one=cs.length===1?cs[0]:null;host.appendChild(E('div','sr16-panel-title',cs.length>1?'Posição · '+cs.length+' elementos':'Posição · '+A.partLabel(one.role)));const grid=E('div','sr16-grid4');grid.append(numField('X',b.x,v=>setBoxDimension('x',v)),numField('Y',b.y,v=>setBoxDimension('y',v)),numField('Largura',b.w,v=>setBoxDimension('w',v)),numField('Altura',b.h,v=>setBoxDimension('h',v)));host.appendChild(grid);const grid2=E('div','sr16-grid4');const rot=one?one.edit.rotation||0:0,op=one?one.edit.opacity??1:1;grid2.append(numField('Rotação °',rot,v=>A.setSelectionRotation(v)),numField('Opacidade %',op*100,v=>A.setSelectionOpacity(v/100)));if(one?.role==='IMAGEM'){grid2.append(numField('Zoom imagem',one.edit.imageScale??1,v=>setPart(one,{imageScale:Math.max(.2,Math.min(5,v||1))}),'.05'),selectField('Encaixe',one.edit.fit||one.base.fit||'contain',[['contain','Mostrar inteira'],['cover','Preencher'],['fill','Esticar']],v=>setPart(one,{fit:v})))}host.appendChild(grid2);const ar=E('div','sr16-btnrow');for(const [t,m] of [['⟸','left'],['↔','center'],['⟹','right'],['⤒','top'],['↕','middle'],['⤓','bottom']])ar.appendChild(B(t,()=>A.alignSelection(m)));host.appendChild(ar);if(cs.length>=3){const d=E('div','sr16-btnrow');d.append(B('Distribuir H',()=>A.distributeSelection('x')),B('Distribuir V',()=>A.distributeSelection('y')));host.appendChild(d)}const actions=E('div','sr16-btnrow');actions.append(B(cs.every(c=>c.edit.locked)?'Desbloquear':'Bloquear',()=>A.lockSelection()),B('Frente',()=>A.layerSelection('front')),B('Trás',()=>A.layerSelection('back')));host.appendChild(actions);host.appendChild(E('div','sr16-hint','Shift + clique seleciona várias partes. Arraste a seleção inteira, use as 8 alças para redimensionar e a alça superior para girar. Duplo clique em texto edita direto; duplo clique na imagem entra no recorte.'))}
function layerPanel(host){const e=A.selectedElement?.(),slot=A.selectedSlot?.();if(!e||!slot)return;host.appendChild(E('div','sr16-panel-title','Camadas'));const roles=A.PART_ROLES.filter(r=>slot.fields?.[r]);roles.sort((a,b)=>{const ca=A.partContext(A.partKey(e.id,a)),cb=A.partContext(A.partKey(e.id,b));return(Number(cb?.edit.z??(b==='IMAGEM'?8:45))-Number(ca?.edit.z??(a==='IMAGEM'?8:45)))});for(const role of roles){const c=A.partContext(A.partKey(e.id,role)),row=E('div','sr16-layer'+(A.state.proSelection.includes(c.k)?' active':''));const name=B((c.edit.hidden?'○ ':'● ')+A.partLabel(role),()=>A.selectPart(e.id,role,'replace'),'name btn');const eye=B(c.edit.hidden?'👁':'◉',()=>{c.edit.hidden=!c.edit.hidden;A.commit()},'btn');const lock=B(c.edit.locked?'🔒':'🔓',()=>{c.edit.locked=!c.edit.locked;A.commit()},'btn');row.append(name,eye,lock);host.appendChild(row)}}
A.renderInspector=()=>{A.inspectorNode.replaceChildren();A.issueNode.replaceChildren();productInspector(A.inspectorNode);positionPanel(A.inspectorNode);layerPanel(A.inspectorNode);const pg=A.page(),issues=A.validate().filter(x=>x.message.startsWith(pg.name+':')).slice(0,6);for(const issue of issues)A.issueNode.appendChild(E('div','issue '+issue.severity,issue.message));renderFloat()};
const oldRenderAll=A.renderAll;A.renderAll=()=>{A.renderCategories();A.renderProducts();A.renderPages();A.renderCanvas();A.renderKPIs();A.renderInspector()};A.listeners?.delete?.(oldRenderAll);A.onChange(A.renderAll);
function shortcut(ev){if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName)||document.activeElement?.isContentEditable)return;const ctrl=ev.ctrlKey||ev.metaKey,key=ev.key;if(key==='Escape'){ev.preventDefault();if(A.state.cropKey){A.state.cropKey=null;A.renderCanvas();renderFloat()}else A.clearProSelection();return}if(key==='Delete'||key==='Backspace'){if(selected().length){ev.preventDefault();ev.stopImmediatePropagation();A.snapshot();A.hideSelection(true)}return}if(ctrl&&key.toLowerCase()==='g'){ev.preventDefault();ev.stopImmediatePropagation();ev.shiftKey?A.ungroupSelection():A.groupSelection();return}if(ctrl&&key.toLowerCase()==='d'){ev.preventDefault();A.duplicateSelectionProduct();return}if(ctrl&&(key===']'||key==='[')){ev.preventDefault();if(key===']')A.layerSelection(ev.altKey?'front':'forward');else A.layerSelection(ev.altKey?'back':'backward');return}if(key===','||key==='.'){if(selected().length){ev.preventDefault();const step=ev.shiftKey?15:1;A.snapshot();for(const c of selected())c.edit.rotation=(Number(c.edit.rotation)||0)+(key==='.'?step:-step);A.commit()}return}const arrows={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]};if(arrows[key]&&selected().length){ev.preventDefault();ev.stopImmediatePropagation();const step=ev.shiftKey?10:1,[x,y]=arrows[key];A.snapshot();A.moveSelection(x*step,y*step,true);return}if(key==='Tab'){const all=A.allPartContexts?.().filter(c=>!c.edit.hidden)||[];if(!all.length)return;ev.preventDefault();const cur=(A.state.proSelection||[])[0],i=Math.max(0,all.findIndex(c=>c.k===cur)),n=all[(i+(ev.shiftKey?-1:1)+all.length)%all.length];A.selectPart(n.eid,n.role,'replace')}}
document.addEventListener('keydown',shortcut,true);
window.addEventListener('resize',renderFloat);A.centerNode.addEventListener('scroll',renderFloat,{passive:true});
A.renderAll();
console.info('[SR Studio] Beta 16 UI estilo Canva ativa');
})();
